#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
citation_index.py

Maintain Argument citation aliases and generated citation JSON indexes.

Default behavior:
  1. Scan citation-eligible Argument pages.
  2. Generate expected citation_aliases from authors + year.
  3. Remove legacy citation_stem/citation_suffix/citation_key/citation_short.
  4. Write citation/citation_full.json and citation/citation_ambiguous.json.

This script does not link body text. Use scripts/citation_linker.py for that.
"""

from __future__ import annotations

import argparse
import json
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
WIKI_DIR = ROOT / "wiki"
ARG_DIR = WIKI_DIR / "arguments"
CITATION_DIR = ROOT / "citation"
FULL_JSON = CITATION_DIR / "citation_full.json"
AMBIG_JSON = CITATION_DIR / "citation_ambiguous.json"

FRONTMATTER_RE = re.compile(r"\A---\s*\n(.*?)\n---\s*\n", re.S)
KEY_RE = re.compile(r"^([A-Za-z0-9_-]+):\s*(.*)$")
LEGACY_FIELDS = {"citation_stem", "citation_suffix", "citation_key", "citation_short"}
GENERATED_NOTE = "Generated by scripts/citation_index.py. Do not edit manually."


@dataclass
class ArgumentCitation:
    path: Path
    title: str
    authors: list[str]
    year: str
    doi: str
    isbn: str
    citation: str
    base_aliases: list[str]
    aliases: list[str]

    @property
    def rel_path(self) -> str:
        return self.path.relative_to(ROOT).as_posix()

    @property
    def target(self) -> str:
        return self.path.stem

    @property
    def base_key(self) -> str:
        return self.base_aliases[0]

    def json_entry(self) -> dict[str, Any]:
        return {
            "argument": self.target,
            "path": self.rel_path,
            "aliases": self.aliases,
            "year": self.year,
            "doi": self.doi,
            "isbn": self.isbn,
            "authors": self.authors,
            "citation": self.citation,
            "title": self.title,
        }


@dataclass
class InheritedBookChapter:
    path: Path
    title: str
    aliases: list[str]
    parent_target: str
    current_part_of: str

    @property
    def rel_path(self) -> str:
        return self.path.relative_to(ROOT).as_posix()


def parse_scalar(value: str) -> str:
    value = value.strip()
    if value in {"", "null", "None", "~"}:
        return ""
    if len(value) >= 2 and value[0] == value[-1] and value[0] in {"'", '"'}:
        inner = value[1:-1]
        return inner.replace("''", "'") if value[0] == "'" else inner
    return value


def parse_inline_list(value: str) -> list[str]:
    inner = value[1:-1].strip()
    if not inner:
        return []
    items: list[str] = []
    current = ""
    quote = ""
    for ch in inner:
        if ch in {"'", '"'}:
            quote = "" if quote == ch else ch if not quote else quote
            current += ch
        elif ch == "," and not quote:
            items.append(parse_scalar(current))
            current = ""
        else:
            current += ch
    if current.strip():
        items.append(parse_scalar(current))
    return [x for x in items if x]


def parse_frontmatter(text: str) -> tuple[dict[str, Any], str, str]:
    m = FRONTMATTER_RE.match(text)
    if not m:
        return {}, "", text
    raw = m.group(1)
    body = text[m.end():]
    data: dict[str, Any] = {}
    lines = raw.splitlines()
    i = 0
    while i < len(lines):
        line = lines[i]
        m_key = KEY_RE.match(line)
        if not m_key:
            i += 1
            continue
        key, val = m_key.group(1), m_key.group(2).strip()
        if val == "":
            items: list[str] = []
            j = i + 1
            while j < len(lines) and re.match(r"^\s*-\s+", lines[j]):
                items.append(parse_scalar(re.sub(r"^\s*-\s+", "", lines[j])))
                j += 1
            data[key] = items if items else ""
            i = j
            continue
        if val.startswith("[") and val.endswith("]"):
            data[key] = parse_inline_list(val)
        else:
            data[key] = parse_scalar(val)
        i += 1
    return data, raw, body


def list_value(value: Any) -> list[str]:
    if isinstance(value, list):
        return [str(x).strip() for x in value if str(x).strip()]
    if isinstance(value, str) and value.strip():
        return [value.strip()]
    return []


def display_from_wikilink(value: str) -> str:
    m = re.fullmatch(r"\[\[([^|\]]+)(?:\|([^\]]+))?\]\]", value.strip())
    if not m:
        return value.strip()
    return (m.group(2) or m.group(1)).strip()


def target_from_wikilink(value: str) -> str:
    m = re.fullmatch(r"\[\[([^|\]]+)(?:\|([^\]]+))?\]\]", value.strip())
    if not m:
        return ""
    return m.group(1).strip()


def author_label(author: str) -> str:
    author = display_from_wikilink(author)
    author = author.replace("''", "'")
    author = re.sub(r"\s+", " ", author).strip()
    if "," in author:
        return author.split(",", 1)[0].strip()
    return author


def author_part(authors: list[str]) -> str:
    labels = [author_label(a) for a in authors if author_label(a)]
    if not labels:
        return ""
    if len(labels) == 1:
        return labels[0]
    if len(labels) == 2:
        return f"{labels[0]} & {labels[1]}"
    return f"{labels[0]} et al."


def has_cjk(text: str) -> bool:
    return bool(re.search(r"[\u3400-\u9fff]", text))


def dedupe(items: list[str]) -> list[str]:
    seen: set[str] = set()
    result: list[str] = []
    for item in items:
        if item and item not in seen:
            result.append(item)
            seen.add(item)
    return result


def chinese_author_part(citation: str, year: str) -> str:
    if not has_cjk(citation) or not year:
        return ""
    m = re.match(rf"^\s*(?P<authors>.+?)\s*(?:[.。]\s*)?[（(]\s*{re.escape(year)}\s*[）)]", citation)
    if not m:
        return ""
    raw = m.group("authors").strip(" ,，.。")
    if not has_cjk(raw):
        return ""
    parts = [p.strip() for p in re.split(r"[、，,；;]\s*", raw) if p.strip()]
    cjk_parts = [p for p in parts if has_cjk(p)]
    if not cjk_parts:
        return ""
    if len(cjk_parts) == 1:
        return cjk_parts[0]
    if len(cjk_parts) == 2:
        return f"{cjk_parts[0]}和{cjk_parts[1]}"
    return f"{cjk_parts[0]}等"


def aliases_for_parts(parts: list[str], year: str) -> list[str]:
    if not parts or not year:
        return []
    aliases: list[str] = []
    for part in parts:
        aliases.extend([f"{part}, {year}", f"{part} ({year})"])
    return dedupe(aliases)


def aliases_for(authors: list[str], year: str, citation: str = "") -> list[str]:
    parts = [author_part(authors)]
    chinese_part = chinese_author_part(citation, re.sub(r"[a-z]$", "", year))
    if chinese_part:
        parts.append(chinese_part)
    parts = [p for p in dedupe(parts) if p]
    return aliases_for_parts(parts, year)


def is_citation_eligible(meta: dict[str, Any], path: Path) -> bool:
    if meta.get("type") != "argument":
        return False
    if meta.get("subtype") == "edited-volume-overview":
        return False
    if inherited_book_chapter_parent(meta, path):
        return False
    if "templates" in path.parts:
        return False
    return bool(str(meta.get("year") or "").strip() and list_value(meta.get("authors")))


def inferred_parent_target_from_filename(path: Path) -> str:
    m = re.match(r"^(Argument_.+)_Ch\d{1,3}(?:[_-].+)?$", path.stem)
    if not m:
        return ""
    parent_target = m.group(1)
    parent_path = path.with_name(f"{parent_target}.md")
    return parent_target if parent_path.exists() else ""


def inherited_book_chapter_parent(meta: dict[str, Any], path: Path) -> str:
    """Chapter Argument for a single authored book; cite the parent book instead."""
    if meta.get("publication_type") != "book-chapter":
        return ""
    if meta.get("subtype") not in {"textbook", "monograph"}:
        return ""
    part_of = str(meta.get("part_of") or "").strip()
    if part_of.startswith("[[Argument_") and part_of.endswith("]]"):
        return target_from_wikilink(part_of)
    return inferred_parent_target_from_filename(path)


def load_arguments() -> tuple[list[ArgumentCitation], list[InheritedBookChapter]]:
    items: list[ArgumentCitation] = []
    inherited_chapters: list[InheritedBookChapter] = []
    if not ARG_DIR.exists():
        return items, inherited_chapters
    for path in sorted(ARG_DIR.rglob("*.md")):
        text = path.read_text(encoding="utf-8", errors="replace")
        meta, _, _ = parse_frontmatter(text)
        parent_target = inherited_book_chapter_parent(meta, path)
        if parent_target:
            inherited_chapters.append(InheritedBookChapter(
                path=path,
                title=str(meta.get("title") or path.stem).strip(),
                aliases=list_value(meta.get("citation_aliases")),
                parent_target=parent_target,
                current_part_of=str(meta.get("part_of") or "").strip(),
            ))
            continue
        if not is_citation_eligible(meta, path):
            continue
        authors = list_value(meta.get("authors"))
        year = str(meta.get("year") or "").strip()
        base = aliases_for(authors, year, str(meta.get("citation") or "").strip())
        if not base:
            continue
        items.append(ArgumentCitation(
            path=path,
            title=str(meta.get("title") or path.stem).strip(),
            authors=authors,
            year=year,
            doi=str(meta.get("doi") or "").strip(),
            isbn=str(meta.get("isbn") or "").strip(),
            citation=str(meta.get("citation") or "").strip(),
            base_aliases=base,
            aliases=base,
        ))
    return items, inherited_chapters


def assign_suffixes(items: list[ArgumentCitation]) -> None:
    groups: dict[str, list[ArgumentCitation]] = {}
    for item in items:
        groups.setdefault(item.base_key, []).append(item)
    for group in groups.values():
        if len(group) == 1:
            group[0].aliases = group[0].base_aliases
            continue
        ordered = sorted(group, key=lambda x: (x.citation, x.title, x.rel_path))
        for idx, item in enumerate(ordered):
            suffix = chr(ord("a") + idx)
            year = f"{item.year}{suffix}"
            item.aliases = aliases_for(item.authors, year, item.citation)


def yaml_quote(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def aliases_block(aliases: list[str]) -> list[str]:
    if not aliases:
        return ["citation_aliases: []"]
    return ["citation_aliases:", *[f"  - {yaml_quote(alias)}" for alias in aliases]]


def replace_frontmatter(text: str, aliases: list[str]) -> str:
    m = FRONTMATTER_RE.match(text)
    if not m:
        return text
    lines = m.group(1).splitlines()
    output: list[str] = []
    inserted = False
    i = 0
    while i < len(lines):
        line = lines[i]
        m_key = KEY_RE.match(line)
        key = m_key.group(1) if m_key else ""
        if key in LEGACY_FIELDS or key == "citation_aliases":
            i += 1
            while i < len(lines) and re.match(r"^\s*-\s+", lines[i]):
                i += 1
            continue
        output.append(line)
        if key == "doi":
            output.extend(aliases_block(aliases))
            inserted = True
        i += 1
    if not inserted:
        insert_at = 0
        for idx, line in enumerate(output):
            m_key = KEY_RE.match(line)
            if m_key and m_key.group(1) in {"year", "citation"}:
                insert_at = idx + 1
        output[insert_at:insert_at] = aliases_block(aliases)
    new_fm = "---\n" + "\n".join(output).rstrip() + "\n---\n"
    return new_fm + text[m.end():]


def replace_scalar_frontmatter_field(text: str, field: str, value: str, after_keys: set[str] | None = None) -> str:
    m = FRONTMATTER_RE.match(text)
    if not m:
        return text
    lines = m.group(1).splitlines()
    output: list[str] = []
    inserted = False
    i = 0
    while i < len(lines):
        line = lines[i]
        m_key = KEY_RE.match(line)
        key = m_key.group(1) if m_key else ""
        if key == field:
            output.append(f"{field}: {yaml_quote(value)}")
            inserted = True
            i += 1
            while i < len(lines) and re.match(r"^\s*-\s+", lines[i]):
                i += 1
            continue
        output.append(line)
        if not inserted and after_keys and key in after_keys:
            next_is_list_item = i + 1 < len(lines) and re.match(r"^\s*-\s+", lines[i + 1])
            if not next_is_list_item:
                output.append(f"{field}: {yaml_quote(value)}")
                inserted = True
        i += 1
    if not inserted:
        output.append(f"{field}: {yaml_quote(value)}")
    new_fm = "---\n" + "\n".join(output).rstrip() + "\n---\n"
    return new_fm + text[m.end():]


def update_argument_files(items: list[ArgumentCitation], dry_run: bool) -> int:
    changed = 0
    for item in items:
        text = item.path.read_text(encoding="utf-8", errors="replace")
        new_text = replace_frontmatter(text, item.aliases)
        if new_text != text:
            changed += 1
            print(f"✏️  {item.rel_path} aliases={item.aliases}")
            if not dry_run:
                item.path.write_text(new_text, encoding="utf-8")
    return changed


def clear_inherited_chapter_aliases(chapters: list[InheritedBookChapter], dry_run: bool) -> int:
    changed = 0
    for chapter in chapters:
        text = chapter.path.read_text(encoding="utf-8", errors="replace")
        new_text = replace_frontmatter(text, [])
        new_text = replace_scalar_frontmatter_field(
            new_text,
            "part_of",
            f"[[{chapter.parent_target}]]",
            after_keys={"sources"},
        )
        if new_text != text:
            changed += 1
            print(f"✏️  {chapter.rel_path} aliases=[] part_of=[[{chapter.parent_target}]]")
            if not dry_run:
                chapter.path.write_text(new_text, encoding="utf-8")
    return changed


def build_indexes(items: list[ArgumentCitation]) -> tuple[dict[str, Any], dict[str, Any]]:
    full: dict[str, Any] = {"_note": GENERATED_NOTE, "items": {}}
    for item in items:
        entry = item.json_entry()
        for alias in item.aliases:
            full["items"][alias] = entry

    ambiguous: dict[str, Any] = {"_note": GENERATED_NOTE, "items": {}}
    groups: dict[str, list[ArgumentCitation]] = {}
    for item in items:
        groups.setdefault(item.base_key, []).append(item)
    for base_key, group in sorted(groups.items()):
        if len(group) > 1:
            ambiguous["items"][base_key] = [item.json_entry() for item in sorted(group, key=lambda x: x.aliases[0])]
    return full, ambiguous


def write_json(full: dict[str, Any], ambiguous: dict[str, Any], dry_run: bool) -> None:
    if dry_run:
        print(f"[dry-run] would write {FULL_JSON.relative_to(ROOT)}")
        print(f"[dry-run] would write {AMBIG_JSON.relative_to(ROOT)}")
        return
    CITATION_DIR.mkdir(parents=True, exist_ok=True)
    FULL_JSON.write_text(json.dumps(full, ensure_ascii=False, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    AMBIG_JSON.write_text(json.dumps(ambiguous, ensure_ascii=False, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(f"✅ wrote {FULL_JSON.relative_to(ROOT)}")
    print(f"✅ wrote {AMBIG_JSON.relative_to(ROOT)}")


def check(items: list[ArgumentCitation]) -> int:
    errors = 0
    seen: dict[str, list[str]] = {}
    for item in items:
        for alias in item.aliases:
            seen.setdefault(alias, []).append(item.rel_path)
    for alias, paths in seen.items():
        if len(paths) > 1:
            print(f"❌ duplicate citation alias {alias!r}: " + ", ".join(paths))
            errors += 1
    return errors


def check_inherited_chapters(chapters: list[InheritedBookChapter]) -> int:
    errors = 0
    for chapter in chapters:
        if chapter.aliases:
            print(f"❌ inherited book chapter should not have citation_aliases: {chapter.rel_path} aliases={chapter.aliases}")
            errors += 1
        expected_part_of = f"[[{chapter.parent_target}]]"
        if chapter.current_part_of != expected_part_of:
            print(f"❌ inherited book chapter part_of should be {expected_part_of}: {chapter.rel_path} got={chapter.current_part_of!r}")
            errors += 1
    return errors


def main() -> int:
    parser = argparse.ArgumentParser(description="Maintain Argument citation aliases and citation JSON indexes.")
    parser.add_argument("--dry-run", action="store_true", help="Preview changes without writing.")
    parser.add_argument("--full", action="store_true", help="Accepted for workflow symmetry; citation indexing is always full.")
    parser.add_argument("--check", action="store_true", help="Check generated alias uniqueness and exit.")
    args = parser.parse_args()

    items, inherited_chapters = load_arguments()
    assign_suffixes(items)
    print(f"📚 citation-eligible arguments: {len(items)}")
    print(f"📖 inherited book chapters: {len(inherited_chapters)}")

    errors = check(items) + check_inherited_chapters(inherited_chapters)
    if args.check:
        return 1 if errors else 0

    changed = update_argument_files(items, dry_run=args.dry_run)
    changed += clear_inherited_chapter_aliases(inherited_chapters, dry_run=args.dry_run)
    print(f"{'[dry-run] ' if args.dry_run else ''}frontmatter files changed: {changed}")
    full, ambiguous = build_indexes(items)
    write_json(full, ambiguous, dry_run=args.dry_run)
    print(f"🔎 citation aliases: {len(full['items'])}")
    print(f"⚖️ ambiguous groups: {len(ambiguous['items'])}")
    return 1 if errors else 0


if __name__ == "__main__":
    raise SystemExit(main())
