#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
citation_index.py

Generate citation indexes and link APA short citations to Argument pages.

Default behavior:
  1. Scan wiki/arguments/ for citation-eligible Argument pages.
  2. Write citation/citation_full.json and citation/citation_ambiguous.json.
  3. Link unlinked APA short citations in wiki/*.md.

Supported citation forms:
  (Ball, 2008a)
  (Ball, 2008a, p. 12)
  (Ball, 2008a, pp. 12–15)
  Ball (2008a)
  Ball (2008a, p. 12)
  Ball (2008a, pp. 12–15)
  (Lindblad & Popkewitz, 2004; Muller, 2004)
  (Lindblad & Popkewitz, 2004, p. 12; Muller, 2004, pp. 33–35)

Safety:
  - Skips YAML frontmatter, code fences, inline code, Obsidian comments, HTML comments, and existing wikilinks.
  - Argument overview pages with subtype: edited-volume-overview are not citation-eligible.
  - Missing or ambiguous citation matches are left unchanged and reported.

Usage:
  python3 scripts/citation_index.py
  python3 scripts/citation_index.py --dry-run
  python3 scripts/citation_index.py --index-only
  python3 scripts/citation_index.py --link-only
  python3 scripts/citation_index.py --full
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional, Tuple

ROOT = Path.cwd()
WIKI_DIR = ROOT / "wiki"
ARG_DIR = WIKI_DIR / "arguments"
CITATION_DIR = ROOT / "citation"
FULL_JSON = CITATION_DIR / "citation_full.json"
AMBIG_JSON = CITATION_DIR / "citation_ambiguous.json"

# Allowed page types for linking. Keep broad because Concept/Theory/etc. now use Argument links as sources.
MD_GLOB_ROOTS = [WIKI_DIR]

FRONTMATTER_RE = re.compile(r"\A---\s*\n(.*?)\n---\s*\n", re.S)
WIKILINK_RE = re.compile(r"\[\[[^\]]+\]\]")
INLINE_CODE_RE = re.compile(r"`[^`]*`")
HTML_COMMENT_RE = re.compile(r"<!--.*?-->", re.S)
OBSIDIAN_COMMENT_RE = re.compile(r"%%.*?%%", re.S)
CODE_FENCE_RE = re.compile(r"```.*?```", re.S)

# Parenthetical citation group, supports ASCII parentheses and common Chinese full-width parentheses.
# We normalize full-width parentheses to ASCII in output only when linking the citation display.
PAREN_GROUP_RE = re.compile(r"(?<!\[)\(([^()\n]*\b\d{4}[a-z]?[^()\n]*)\)")
FULLWIDTH_PAREN_GROUP_RE = re.compile(r"（([^（）\n]*\b\d{4}[a-z]?[^（）\n]*)）")

# Narrative form: Ball (2008a, p. 12), Lindblad & Popkewitz (2004)
NARRATIVE_RE = re.compile(
    r"(?<![\w\]\)])"
    r"(?P<author>[A-Z][A-Za-zÀ-ÖØ-öø-ÿ'’.-]+(?:\s+(?:&|and)\s+[A-Z][A-Za-zÀ-ÖØ-öø-ÿ'’.-]+|\s+et\s+al\.)?)"
    r"\s*\("
    r"(?P<year>\d{4}[a-z]?)"
    r"(?P<locator>\s*,\s*(?:p\.|pp\.)\s*[^)]+)?"
    r"\)"
)

# Single item inside parenthetical group.
# Allows Author, 2008a, p. 12 ; Author & Author, 2008, pp. 12–15
PAREN_ITEM_RE = re.compile(
    r"^\s*"
    r"(?P<author>[A-Z][A-Za-zÀ-ÖØ-öø-ÿ'’.-]+(?:\s+(?:&|and)\s+[A-Z][A-Za-zÀ-ÖØ-öø-ÿ'’.-]+|\s+et\s+al\.)?)"
    r"\s*,\s*"
    r"(?P<year>\d{4}[a-z]?)"
    r"(?P<locator>\s*,\s*(?:p\.|pp\.)\s*.+)?"
    r"\s*$"
)

GENERATED_NOTE = "Generated by scripts/citation_index.py. Do not edit manually."


@dataclass
class CitationEntry:
    citation_key: str
    citation_stem: str
    citation_short: str
    citation_suffix: str
    citation_name: str
    year: str
    title: str
    path: str
    file_stem: str
    doi: str = ""
    authors: List[str] = None
    subtype: str = ""
    publication_type: str = ""
    citation: str = ""

    def to_json(self) -> Dict[str, Any]:
        return {
            "citation_key": self.citation_key,
            "citation_stem": self.citation_stem,
            "citation_short": self.citation_short,
            "citation_suffix": self.citation_suffix,
            "citation_name": self.citation_name,
            "year": self.year,
            "title": self.title,
            "argument": self.file_stem,
            "argument_path": self.path,
            "doi": self.doi,
            "authors": self.authors or [],
            "subtype": self.subtype,
            "publication_type": self.publication_type,
            "citation": self.citation,
        }


def run_git_changed() -> Optional[List[Path]]:
    try:
        result = subprocess.run(
            ["git", "diff", "--name-only", "HEAD"],
            cwd=ROOT,
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.DEVNULL,
            check=False,
        )
        if result.returncode != 0:
            return None
        paths = []
        for line in result.stdout.splitlines():
            p = ROOT / line.strip()
            if p.suffix.lower() == ".md" and WIKI_DIR in p.parents and p.exists():
                paths.append(p)
        return paths
    except Exception:
        return None


def parse_scalar(value: str) -> str:
    value = value.strip()
    if value in {"", "null", "None", "~"}:
        return ""
    if (value.startswith('"') and value.endswith('"')) or (value.startswith("'") and value.endswith("'")):
        return value[1:-1]
    return value


def parse_frontmatter(text: str) -> Tuple[Dict[str, Any], str, str]:
    m = FRONTMATTER_RE.match(text)
    if not m:
        return {}, "", text
    raw = m.group(1)
    body = text[m.end():]
    data: Dict[str, Any] = {}
    lines = raw.splitlines()
    i = 0
    while i < len(lines):
        line = lines[i]
        if not line.strip() or line.lstrip().startswith("#"):
            i += 1
            continue
        if re.match(r"^[A-Za-z0-9_\-]+:\s*", line):
            key, val = line.split(":", 1)
            key = key.strip()
            val = val.strip()
            if val == "":
                items: List[str] = []
                j = i + 1
                while j < len(lines) and re.match(r"^\s+-\s+", lines[j]):
                    item = re.sub(r"^\s+-\s+", "", lines[j]).strip()
                    items.append(parse_scalar(item))
                    j += 1
                if items:
                    data[key] = items
                    i = j
                    continue
                data[key] = ""
            elif val.startswith("[") and val.endswith("]"):
                # Simple inline YAML list support.
                inner = val[1:-1].strip()
                if not inner:
                    data[key] = []
                else:
                    parts = [parse_scalar(x.strip()) for x in inner.split(",")]
                    data[key] = parts
            else:
                data[key] = parse_scalar(val)
        i += 1
    return data, raw, body


def is_citation_eligible(meta: Dict[str, Any], path: Path) -> bool:
    if meta.get("type") != "argument":
        return False
    if meta.get("subtype") == "edited-volume-overview":
        return False
    if not str(path).endswith(".md"):
        return False
    required = ["citation_key", "citation_stem", "citation_short", "year"]
    return all(str(meta.get(k, "")).strip() for k in required)


def normalize_author_key(author: str) -> str:
    author = author.strip()
    author = author.replace(" and ", " & ")
    author = re.sub(r"\s+", " ", author)
    return author


def normalize_year(year: str) -> str:
    return year.strip()


def stem_from_short(citation_short: str) -> Optional[str]:
    # Ball, 2008a -> Ball|2008 ; Lindblad & Popkewitz, 2004 -> Lindblad & Popkewitz|2004
    m = re.match(r"^(.+?),\s*(\d{4})([a-z]?)$", citation_short.strip())
    if not m:
        return None
    return f"{normalize_author_key(m.group(1))}|{m.group(2)}"


def load_citation_entries() -> List[CitationEntry]:
    entries: List[CitationEntry] = []
    if not ARG_DIR.exists():
        return entries
    for path in sorted(ARG_DIR.rglob("*.md")):
        text = path.read_text(encoding="utf-8", errors="replace")
        meta, _, _ = parse_frontmatter(text)
        if not is_citation_eligible(meta, path):
            continue
        short = str(meta.get("citation_short", "")).strip()
        year_match = re.search(r"\b(\d{4}[a-z]?)\b", short)
        year_full = year_match.group(1) if year_match else str(meta.get("year", "")).strip()
        year_base = re.match(r"(\d{4})", year_full).group(1) if re.match(r"(\d{4})", year_full) else str(meta.get("year", "")).strip()
        citation_name = short.rsplit(",", 1)[0].strip() if "," in short else str(meta.get("citation_name", "")).strip()
        authors = meta.get("authors", [])
        if isinstance(authors, str):
            authors = [authors] if authors else []
        entries.append(CitationEntry(
            citation_key=str(meta.get("citation_key", "")).strip(),
            citation_stem=str(meta.get("citation_stem", "")).strip() or stem_from_short(short) or "",
            citation_short=short,
            citation_suffix=str(meta.get("citation_suffix", "")).strip(),
            citation_name=citation_name,
            year=str(meta.get("year", year_base)).strip(),
            title=str(meta.get("title", path.stem)).strip(),
            path=str(path.relative_to(ROOT)),
            file_stem=path.stem,
            doi=str(meta.get("doi", "")).strip(),
            authors=authors,
            subtype=str(meta.get("subtype", "")).strip(),
            publication_type=str(meta.get("publication_type", "")).strip(),
            citation=str(meta.get("citation", "")).strip(),
        ))
    return entries


def write_indexes(entries: List[CitationEntry], dry_run: bool = False) -> Tuple[Dict[str, Any], Dict[str, Any]]:
    by_key = {e.citation_key: e.to_json() for e in entries}
    stems: Dict[str, List[Dict[str, Any]]] = {}
    for e in entries:
        stems.setdefault(e.citation_stem, []).append(e.to_json())
    ambiguous = {stem: vals for stem, vals in stems.items() if len(vals) > 1}
    full_obj = {"_note": GENERATED_NOTE, "items": by_key, "by_stem": stems}
    amb_obj = {"_note": GENERATED_NOTE, "items": ambiguous}
    if not dry_run:
        CITATION_DIR.mkdir(parents=True, exist_ok=True)
        FULL_JSON.write_text(json.dumps(full_obj, ensure_ascii=False, indent=2, sort_keys=True) + "\n", encoding="utf-8")
        AMBIG_JSON.write_text(json.dumps(amb_obj, ensure_ascii=False, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    return full_obj, amb_obj


def build_lookup(entries: List[CitationEntry]) -> Dict[str, CitationEntry]:
    lookup: Dict[str, CitationEntry] = {}
    for e in entries:
        # Full short includes suffix when needed.
        lookup[e.citation_short] = e
        # Also support short reconstructed from citation_name + year/suffix.
        y = f"{e.year}{e.citation_suffix}" if e.citation_suffix and not str(e.year).endswith(e.citation_suffix) else str(e.year)
        lookup[f"{e.citation_name}, {y}"] = e
    return lookup


def mask_protected(text: str) -> Tuple[str, List[str]]:
    protected: List[str] = []
    def repl(m: re.Match) -> str:
        protected.append(m.group(0))
        return f"\uE000{len(protected)-1}\uE001"
    # order matters: code fences first, wikilinks before bracket processing.
    for rx in [CODE_FENCE_RE, HTML_COMMENT_RE, OBSIDIAN_COMMENT_RE, WIKILINK_RE, INLINE_CODE_RE]:
        text = rx.sub(repl, text)
    return text, protected


def unmask(text: str, protected: List[str]) -> str:
    def repl(m: re.Match) -> str:
        idx = int(m.group(1))
        return protected[idx]
    return re.sub("\uE000(\d+)\uE001", repl, text)


def split_frontmatter(text: str) -> Tuple[str, str]:
    m = FRONTMATTER_RE.match(text)
    if not m:
        return "", text
    return text[:m.end()], text[m.end():]


def citation_item_key(author: str, year_full: str) -> str:
    return f"{normalize_author_key(author)}, {normalize_year(year_full)}"


def link_target(entry: CitationEntry, display: str) -> str:
    return f"[[{entry.file_stem}|{display}]]"


def link_parenthetical_group(content: str, lookup: Dict[str, CitationEntry], stats: Dict[str, int], missing: List[str]) -> Optional[str]:
    # Split by semicolons. If there is no semicolon, still process as a single item.
    parts = content.split(";")
    linked_parts: List[str] = []
    changed = False
    for raw in parts:
        item = raw.strip()
        if not item:
            linked_parts.append(raw)
            continue
        m = PAREN_ITEM_RE.match(item)
        if not m:
            # If the group has non-citation material, leave whole group unchanged.
            return None
        author = normalize_author_key(m.group("author"))
        year = normalize_year(m.group("year"))
        locator = m.group("locator") or ""
        key = citation_item_key(author, year)
        entry = lookup.get(key)
        if not entry:
            missing.append(key)
            linked_parts.append(item)
            continue
        display = f"{author}, {year}{locator}"
        linked_parts.append(link_target(entry, display))
        changed = True
    if not changed:
        return None
    stats["linked_parenthetical"] += 1
    return "(" + "; ".join(linked_parts) + ")"


def link_parenthetical_matches(text: str, lookup: Dict[str, CitationEntry], stats: Dict[str, int], missing: List[str]) -> str:
    def repl_ascii(m: re.Match) -> str:
        original = m.group(0)
        content = m.group(1)
        if "[[" in original or "]]" in original:
            return original
        linked = link_parenthetical_group(content, lookup, stats, missing)
        return linked if linked else original

    def repl_fullwidth(m: re.Match) -> str:
        original = m.group(0)
        content = m.group(1)
        if "[[" in original or "]]" in original:
            return original
        linked = link_parenthetical_group(content, lookup, stats, missing)
        return linked if linked else original

    text = PAREN_GROUP_RE.sub(repl_ascii, text)
    text = FULLWIDTH_PAREN_GROUP_RE.sub(repl_fullwidth, text)
    return text


def link_narrative_matches(text: str, lookup: Dict[str, CitationEntry], stats: Dict[str, int], missing: List[str]) -> str:
    def repl(m: re.Match) -> str:
        original = m.group(0)
        author = normalize_author_key(m.group("author"))
        year = normalize_year(m.group("year"))
        locator = m.group("locator") or ""
        key = citation_item_key(author, year)
        entry = lookup.get(key)
        if not entry:
            missing.append(key)
            return original
        display = f"{author} ({year}{locator})"
        stats["linked_narrative"] += 1
        return link_target(entry, display)
    return NARRATIVE_RE.sub(repl, text)


def link_citations_in_text(text: str, lookup: Dict[str, CitationEntry], stats: Dict[str, int], missing: List[str]) -> str:
    fm, body = split_frontmatter(text)
    masked, protected = mask_protected(body)
    # Parenthetical first to avoid narrative matching inside groups.
    masked = link_parenthetical_matches(masked, lookup, stats, missing)
    masked = link_narrative_matches(masked, lookup, stats, missing)
    body2 = unmask(masked, protected)
    return fm + body2


def iter_target_markdown(full: bool) -> List[Path]:
    if full:
        paths = []
        for root in MD_GLOB_ROOTS:
            if root.exists():
                paths.extend(root.rglob("*.md"))
        return sorted(set(paths))
    changed = run_git_changed()
    if changed:
        return sorted(set(changed))
    paths = []
    for root in MD_GLOB_ROOTS:
        if root.exists():
            paths.extend(root.rglob("*.md"))
    return sorted(set(paths))


def should_skip_path(path: Path) -> bool:
    parts = set(path.parts)
    if "templates" in parts:
        return True
    if path.name in {"index.md"}:
        return True
    return False


def sync_links(entries: List[CitationEntry], full: bool = False, dry_run: bool = False) -> Tuple[int, Dict[str, int], List[str]]:
    lookup = build_lookup(entries)
    files_changed = 0
    stats = {"linked_parenthetical": 0, "linked_narrative": 0}
    missing: List[str] = []
    for path in iter_target_markdown(full=full):
        if should_skip_path(path):
            continue
        text = path.read_text(encoding="utf-8", errors="replace")
        before_stats = dict(stats)
        new_text = link_citations_in_text(text, lookup, stats, missing)
        if new_text != text:
            files_changed += 1
            rel = path.relative_to(ROOT)
            delta_parenth = stats["linked_parenthetical"] - before_stats["linked_parenthetical"]
            delta_narr = stats["linked_narrative"] - before_stats["linked_narrative"]
            print(f"✏️  {rel}  parenthetical={delta_parenth} narrative={delta_narr}")
            if not dry_run:
                path.write_text(new_text, encoding="utf-8")
    missing_unique = sorted(set(missing))
    return files_changed, stats, missing_unique


def check_entries(entries: List[CitationEntry]) -> int:
    errors = 0
    by_key: Dict[str, List[CitationEntry]] = {}
    by_short: Dict[str, List[CitationEntry]] = {}
    by_stem: Dict[str, List[CitationEntry]] = {}
    for e in entries:
        by_key.setdefault(e.citation_key, []).append(e)
        by_short.setdefault(e.citation_short, []).append(e)
        by_stem.setdefault(e.citation_stem, []).append(e)
        if not re.match(r"^.+?\|\d{4}$", e.citation_stem):
            print(f"❌ bad citation_stem: {e.path} -> {e.citation_stem}")
            errors += 1
        if not re.search(r",\s*\d{4}[a-z]?$", e.citation_short):
            print(f"❌ bad citation_short: {e.path} -> {e.citation_short}")
            errors += 1
    for k, vals in by_key.items():
        if len(vals) > 1:
            print(f"❌ duplicate citation_key {k}: " + ", ".join(v.path for v in vals))
            errors += 1
    for k, vals in by_short.items():
        if len(vals) > 1:
            print(f"❌ duplicate citation_short {k}: " + ", ".join(v.path for v in vals))
            errors += 1
    for stem, vals in by_stem.items():
        if len(vals) > 1:
            suffixes = [v.citation_suffix for v in vals]
            if any(not s for s in suffixes):
                print(f"❌ ambiguous stem without suffix {stem}: " + ", ".join(v.path for v in vals))
                errors += 1
    return errors


def main() -> int:
    ap = argparse.ArgumentParser(description="Generate citation indexes and link APA short citations.")
    ap.add_argument("--dry-run", action="store_true", help="Preview changes without writing files.")
    ap.add_argument("--full", action="store_true", help="Process all wiki markdown files for citation linking.")
    ap.add_argument("--index-only", action="store_true", help="Only generate citation JSON indexes.")
    ap.add_argument("--link-only", action="store_true", help="Only link citations, keeping existing/generated indexes untouched.")
    ap.add_argument("--check", action="store_true", help="Check citation metadata consistency and exit non-zero on errors.")
    args = ap.parse_args()

    entries = load_citation_entries()
    print(f"📚 citation-eligible arguments: {len(entries)}")

    errors = check_entries(entries)
    if args.check:
        if errors:
            print(f"❌ citation metadata errors: {errors}")
            return 1
        print("✅ citation metadata ok")
        return 0

    if not args.link_only:
        write_indexes(entries, dry_run=args.dry_run)
        if args.dry_run:
            print(f"[dry-run] would write {FULL_JSON.relative_to(ROOT)} and {AMBIG_JSON.relative_to(ROOT)}")
        else:
            print(f"✅ wrote {FULL_JSON.relative_to(ROOT)}")
            print(f"✅ wrote {AMBIG_JSON.relative_to(ROOT)}")

    if not args.index_only:
        changed, stats, missing = sync_links(entries, full=args.full, dry_run=args.dry_run)
        if args.dry_run:
            print(f"[dry-run] files that would change: {changed}")
        else:
            print(f"✅ files changed: {changed}")
        print(f"🔗 linked parenthetical groups: {stats['linked_parenthetical']}")
        print(f"🔗 linked narrative citations: {stats['linked_narrative']}")
        if missing:
            print("⚠️  unresolved citation keys:")
            for item in missing[:200]:
                print(f"  - {item}")
            if len(missing) > 200:
                print(f"  ... {len(missing)-200} more")

    return 1 if errors else 0


if __name__ == "__main__":
    raise SystemExit(main())
