import re

path = 'wiki/arguments/books/Creswell_2022_SAGE/Argument_Creswell_2022_SAGE.md'
with open(path, 'r', encoding='utf-8') as f:
    content = f.read()

translations = {
    '"Theory can be a prediction of what the researcher expects to find or an inductive or deductive framework for a study. It may be presented as a model or diagram of the relationship among [[Variable|variables]] or [[Construct|constructs]]. It may exist as generalizations from findings, or a call for action, such as a change-oriented social agenda for a population or society."': '“理论可以是研究者预期发现的预测，或是研究的归纳或演绎框架。它可以作为[[Variable|变量]]或[[Construct|构念]]之间关系的模型或图表呈现。它可以作为发现的概括而存在，也可以是行动的呼吁，例如针对某一人群或社会的变革导向的社会议程。”\n> ("Theory can be a prediction of what the researcher expects to find or an inductive or deductive framework for a study. It may be presented as a model or diagram of the relationship among [[Variable|variables]] or [[Construct|constructs]]. It may exist as generalizations from findings, or a call for action, such as a change-oriented social agenda for a population or society.")',

    '"The metaphor of a rainbow can help visualize how a theory operates. Assume that the rainbow bridges the independent and dependent variables (or constructs). This rainbow ties together the variables and provides an overarching explanation for how and why one would expect the independent variables to explain or predict the dependent variables."': '“彩虹的比喻可以帮助想象理论是如何运作的。假设彩虹在自变量和因变量（或构念）之间架起了一座桥梁。这条彩虹将变量联系在一起，并为我们为何以及如何预期自变量能解释或预测因变量提供了一个总体解释。”\n> ("The metaphor of a rainbow can help visualize how a theory operates. Assume that the rainbow bridges the independent and dependent variables (or constructs). This rainbow ties together the variables and provides an overarching explanation for how and why one would expect the independent variables to explain or predict the dependent variables.")',

    '"Theory develops as an explanation to advance knowledge in fields."': '“理论作为一种解释而发展，以推进各个领域的知识。”\n> ("Theory develops as an explanation to advance knowledge in fields.")',

    '"A variable refers to a characteristic or attribute of an individual or an organization that researchers can measure or observe and varies among the individuals or organizations."': '“变量指的是个体或组织的一种特征或属性，研究者可以对其进行测量或观察，并且这种特征或属性在不同的个体或组织之间存在差异。”\n> ("A variable refers to a characteristic or attribute of an individual or an organization that researchers can measure or observe and varies among the individuals or organizations.")',

    '"One critically important consideration in evaluating causal claims is whether an unmeasured third variable Z may cause the outcome."': '“评估因果主张时一个极其重要的考量是，是否存在一个未被测量的第三变量Z可能导致了该结果。”\n> ("One critically important consideration in evaluating causal claims is whether an unmeasured third variable Z may cause the outcome.")',

    '"Researchers increasingly use a [[Theoretical Standpoint]] in [[Qualitative Research]] to provide an overall orienting lens for the study questions about gender, class, and race (or other issues of marginalized groups). This lens becomes a transformative perspective to bring about change, lift the voices of underrepresented groups, and uncover largely hidden assumptions of individuals."': '“研究者越来越多地在[[Qualitative Research|质性研究]]中使用[[Theoretical Standpoint|理论立场]]，为关于性别、阶级和种族（或边缘群体的其他议题）的研究问题提供一个总体的导向透镜。这种透镜成为一种变革性的视角，旨在带来改变、提升未被充分代表群体的声音，并揭示个体通常隐藏的假设。”\n> ("Researchers increasingly use a [[Theoretical Standpoint]] in [[Qualitative Research]] to provide an overall orienting lens for the study questions about gender, class, and race (or other issues of marginalized groups). This lens becomes a transformative perspective to bring about change, lift the voices of underrepresented groups, and uncover largely hidden assumptions of individuals.")',

    '"Building empirically [[Grounded Theory]] requires a reciprocal relationship between data and theory. Data must be allowed to generate propositions in a dialectical manner permitting a priori theoretical frameworks, but which keeps a framework from becoming the container into which the data must be poured."': '“构建以实证为基础的[[Grounded Theory|扎根理论]]需要数据与理论之间存在互惠关系。必须允许数据以辩证的方式生成命题，这既允许存在先验的理论框架，又防止该框架变成只能把数据倒进去的容器。”\n> ("Building empirically [[Grounded Theory]] requires a reciprocal relationship between data and theory. Data must be allowed to generate propositions in a dialectical manner permitting a priori theoretical frameworks, but which keeps a framework from becoming the container into which the data must be poured.")',

    '"Qualitative research is an inductive process building from data, to broad themes, and to a generalized model or theory."': '“质性研究是一个归纳的过程，从数据建构出广泛的主题，再建构出普遍化的模型或理论。”\n> ("Qualitative research is an inductive process building from data, to broad themes, and to a generalized model or theory.")',

    '"No qualitative study begins from pure observation, and prior conceptual structure composed of theory and method often provides the starting point for all observations."': '“没有任何质性研究始于纯粹的观察，由理论和方法组成的先前概念结构通常为所有观察提供了起点。”\n> ("No qualitative study begins from pure observation, and prior conceptual structure composed of theory and method often provides the starting point for all observations.")',

    '"A worldview relates to the beliefs and values of the researcher and how these inform a study. Theories, in contrast, are less [[Abstract]], drawn from the literature, and provide a guiding perspective for designing many research process aspects."': '“世界观涉及研究者的信念和价值观，以及这些如何指导一项研究。相比之下，理论不那么[[Abstract|抽象]]，它们来自文献，并为设计许多研究过程方面提供了指导视角。”\n> ("A worldview relates to the beliefs and values of the researcher and how these inform a study. Theories, in contrast, are less [[Abstract]], drawn from the literature, and provide a guiding perspective for designing many research process aspects.")',

    '"Part I addresses several preliminary considerations that are necessary before designing a proposal or a plan for a study. These considerations relate to selecting an appropriate research approach, reviewing the literature to position the proposed study within the existing literature, deciding on whether to use a theory in the study, and employing—at the outset—good writing and ethical practices."': '“第一部分讨论了在设计研究计划或方案之前必须考虑的几个初步因素。这些考虑涉及选择合适的研究路径、审查文献以将拟议的研究置于现有文献之中、决定是否在研究中使用理论，以及在开始时就采用良好的写作和伦理实践。”\n> ("Part I addresses several preliminary considerations that are necessary before designing a proposal or a plan for a study. These considerations relate to selecting an appropriate research approach, reviewing the literature to position the proposed study within the existing literature, deciding on whether to use a theory in the study, and employing—at the outset—good writing and ethical practices.")',

    '"Qualitative research is an approach for exploring and understanding the meaning individuals or groups ascribe to a social or human problem. The research process involves emerging questions and procedures, data typically collected in the participant\'s [[Tracking|setting]], data analysis inductively building from particulars to general themes, and the researcher making interpretations of the meaning of the data."': '“质性研究是一种探索和理解个体或群体赋予社会或人类问题的意义的路径。研究过程包括不断涌现的问题和程序，通常在参与者的[[Tracking|自然情境]]中收集数据，通过归纳从细节建构总体主题的数据分析，以及研究者对数据意义做出解释。”\n> ("Qualitative research is an approach for exploring and understanding the meaning individuals or groups ascribe to a social or human problem. The research process involves emerging questions and procedures, data typically collected in the participant\'s [[Tracking|setting]], data analysis inductively building from particulars to general themes, and the researcher making interpretations of the meaning of the data.")',

    '"[[Quantitative Research]] is an approach for testing objective theories by examining the relationship among variables or a comparison among groups. These variables, in turn, can be measured, typically on instruments, so that numbered data can be analyzed using statistical procedures."': '“[[Quantitative Research|量化研究]]是一种通过考察变量间关系或比较群体来检验客观理论的路径。这些变量反过来可以被测量，通常使用工具进行，这样就可以使用统计程序分析数值化数据。”\n> ("[[Quantitative Research]] is an approach for testing objective theories by examining the relationship among variables or a comparison among groups. These variables, in turn, can be measured, typically on instruments, so that numbered data can be analyzed using statistical procedures.")',

    '"Mixed methods research is an approach to inquiry involving collecting both quantitative and qualitative data, using a specific procedure or design, combining (or integrating) the two forms of data within the design, and drawing conclusions (metainferences) about the insight to emerge from the combined databases."': '“混合方法研究是一种探究路径，涉及收集量化和质性两类数据，使用特定的程序或设计，在该设计内合并（或整合）这两种形式的数据，并得出关于从合并数据库中涌现的洞见的结论（元推论）。”\n> ("Mixed methods research is an approach to inquiry involving collecting both quantitative and qualitative data, using a specific procedure or design, combining (or integrating) the two forms of data within the design, and drawing conclusions (metainferences) about the insight to emerge from the combined databases.")',

    '"We have chosen to use the term worldview as meaning \'a basic set of beliefs that guide action\' ([[Egon G. Guba|Guba]], 1990, p. 17)."': '“我们选择使用‘世界观’一词，意思是‘指导行动的一套基本信念’（[[Egon G. Guba|Guba]], 1990, p. 17）。”\n> ("We have chosen to use the term worldview as meaning \'a basic set of beliefs that guide action\' ([[Egon G. Guba|Guba]], 1990, p. 17).")',

    '"Although philosophical ideas remain largely hidden in research, they still influence the practice of research and need to be identified."': '“尽管哲学观念在研究中很大程度上是隐藏的，但它们仍然影响着研究实践，需要被识别出来。”\n> ("Although philosophical ideas remain largely hidden in research, they still influence the practice of research and need to be identified.")',

    '"This book advances a framework, a process, and compositional approaches for designing a proposal or research project for qualitative, quantitative, and mixed methods research in the human, health, and social sciences."': '“本书提出了一套框架、过程和写作方法，用于在人类科学、健康科学和社会科学领域设计质性、量化和混合方法研究计划或项目。”\n> ("This book advances a framework, a process, and compositional approaches for designing a proposal or research project for qualitative, quantitative, and mixed methods research in the human, health, and social sciences.")',

    '"Mixed methods research involves the collection and \'mixing\' or integration of both quantitative and qualitative data in a study. It is not enough to only analyze your qualitative and quantitative data. Further analysis comprises integrating the two databases for additional insight into [[Research Problem|research problems]] and questions."': '“混合方法研究涉及在一项研究中收集并‘混合’或整合量化和质性两类数据。仅仅分析你的质性和量化数据是不够的。进一步的分析包括整合这两个数据库，以获得对[[Research Problem|研究问题]]的额外洞见。”\n> ("Mixed methods research involves the collection and \'mixing\' or integration of both quantitative and qualitative data in a study. It is not enough to only analyze your qualitative and quantitative data. Further analysis comprises integrating the two databases for additional insight into [[Research Problem|research problems]] and questions.")',

    '"This book is not a detailed method text; instead, we highlight the essential features of research design. We have attempted to reduce research to its core ideas so that researchers can plan a thorough and thoughtful study."': '“本书不是一本详细的方法论教材；相反，我们强调研究设计的核心特征。我们试图将研究简化为其核心理念，以便研究者能够规划一项彻底而深思熟虑的研究。”\n> ("This book is not a detailed method text; instead, we highlight the essential features of research design. We have attempted to reduce research to its core ideas so that researchers can plan a thorough and thoughtful study.")',

    '"Designing a study is a difficult and time-consuming process. This book will not necessarily make the process easier or faster, but it can provide specific skills useful in research, knowledge about the steps involved in the process, and a practical guide to composing and writing scholarly research."': '“设计一项研究是一个困难且耗时的过程。本书不一定会让这个过程变得更容易或更快，但它可以提供在研究中有用的具体技能、关于该过程所涉及步骤的知识，以及撰写学术研究的实用指南。”\n> ("Designing a study is a difficult and time-consuming process. This book will not necessarily make the process easier or faster, but it can provide specific skills useful in research, knowledge about the steps involved in the process, and a practical guide to composing and writing scholarly research.")',

    '"Good, sound research projects begin with straightforward, uncomplicated thoughts that readers can easily understand."': '“优秀、扎实的研究项目始于直截了当、毫不复杂的想法，以便读者能够轻松理解。”\n> ("Good, sound research projects begin with straightforward, uncomplicated thoughts that readers can easily understand.")',

    '"A first step in any project is to spend considerable time in the library examining the research on a topic. This point cannot be overemphasized."': '“任何项目的首要步骤都是在图书馆花大量时间查阅关于某一主题的研究文献。这一点再怎么强调都不为过。”\n> ("A first step in any project is to spend considerable time in the library examining the research on a topic. This point cannot be overemphasized.")',

    '"The [[Literature Review]] shares with the reader the results of other studies that are closely related to the one being undertaken. It relates a study to the larger, ongoing dialogue in the literature, filling in gaps and extending prior studies."': '“[[Literature Review|文献综述]]与读者分享了与当前正在进行的研究密切相关的其他研究的结果。它将一项研究与文献中更大规模、正在进行的对话联系起来，填补空白并扩展先前的研究。”\n> ("The [[Literature Review]] shares with the reader the results of other studies that are closely related to the one being undertaken. It relates a study to the larger, ongoing dialogue in the literature, filling in gaps and extending prior studies.")',

    '"The words of an everyday language are rich in multiple meanings. Like other symbols, their power comes from the combination of meaning in a specific setting. . . . Scientific language ostensibly strips this [[Multiplicity]] of meaning from words in the interest of precision."': '“日常语言中的词汇具有丰富的多重含义。就像其他符号一样，它们的力量来自于特定情境中意义的组合……科学语言表面上出于精确性的考虑，剥离了词汇的这种[[Multiplicity|多重性]]意义。”\n> ("The words of an everyday language are rich in multiple meanings. Like other symbols, their power comes from the combination of meaning in a specific setting. . . . Scientific language ostensibly strips this [[Multiplicity]] of meaning from words in the interest of precision.")',

    '"In qualitative research, use the literature sparingly in the beginning to convey an inductive design unless the design type requires a substantial literature orientation at the outset."': '“在质性研究中，除非设计类型要求在开始时就有大量的文献导向，否则在开头应少量使用文献，以传达一种归纳性的设计。”\n> ("In qualitative research, use the literature sparingly in the beginning to convey an inductive design unless the design type requires a substantial literature orientation at the outset.")',

    '"Work on one section often prompts ideas for other sections. First develop an outline, and then write something for each section rapidly to get ideas down on paper. Then refine the sections as you consider the information that should go into each one in more detail."': '“撰写某个部分的工作往往会激发出关于其他部分的想法。首先拟定一个大纲，然后快速为每个部分写点东西，把想法落实到纸上。之后，在你更详细地考虑每个部分应该包含的信息时，再对这些部分进行打磨。”\n> ("Work on one section often prompts ideas for other sections. First develop an outline, and then write something for each section rapidly to get ideas down on paper. Then refine the sections as you consider the information that should go into each one in more detail.")',

    '"One wants a room with no view, so imagination can meet memory in the dark."': '“人需要一个没有风景的房间，这样想象力才能在黑暗中与记忆相遇。”\n> ("One wants a room with no view, so imagination can meet memory in the dark.")',

    '"If you feel you do not have time for [[Writing Habit|regular writing]], begin with reflection on daily activities for a week or two in half-hour blocks. This reflection will likely lead to time to write."': '“如果你觉得自己没有时间进行[[Writing Habit|规律写作]]，可以先从每天留出半小时反思日常活动开始，坚持一两周。这种反思很可能会为你带来写作的时间。”\n> ("If you feel you do not have time for [[Writing Habit|regular writing]], begin with reflection on daily activities for a week or two in half-hour blocks. This reflection will likely lead to time to write.")',

    '"Write while you are fresh during the day or night. Avoid writing in binges. Write in small, regular amounts."': '“在你白天或晚上精神最饱满的时候写作。避免狂饮式写作（突击写作）。要进行少量且规律的写作。”\n> ("Write while you are fresh during the day or night. Avoid writing in binges. Write in small, regular amounts.")',

    '"The eye does not pause and the mind does not stumble in good writing. The prose moves along quickly."': '“在好的写作中，眼睛不会停顿，思维也不会磕绊。文字会流畅快速地推进。”\n> ("The eye does not pause and the mind does not stumble in good writing. The prose moves along quickly.")',

    '"Research involves collecting data from and about people, leading to difficult ethical issues. Writing about these ethical issues is a cornerstone of good research writing."': '“研究涉及从人们那里收集数据以及收集关于人们的数据，这会引发艰难的伦理问题。撰写关于这些伦理问题的内容是优秀研究写作的基石。”\n> ("Research involves collecting data from and about people, leading to difficult ethical issues. Writing about these ethical issues is a cornerstone of good research writing.")',

    '"The introduction is the part of the paper that provides readers with the background information for the research reported in the paper. Its purpose is to establish a framework for the research, so that readers can understand how it is related to other research."': '“引言是论文中为读者提供所报告研究背景信息的部分。其目的是为研究建立一个框架，使读者能够理解该研究如何与其他研究相关联。”\n> ("The introduction is the part of the paper that provides readers with the background information for the research reported in the paper. Its purpose is to establish a framework for the research, so that readers can understand how it is related to other research.")',

    '"The abstract can be the most important single paragraph in a study. It needs to be accurate, non-evaluative, coherent, readable, and concise."': '“摘要可能是研究中最重要的一段话。它必须准确、非评价性、连贯、易读且简洁。”\n> ("The abstract can be the most important single paragraph in a study. It needs to be accurate, non-evaluative, coherent, readable, and concise.")',

    '"We use the metaphor of the writer lowering a barrel into a well. The beginning writer plunges the barrel (the reader) into the depths of the well (the article). The reader sees only unfamiliar material. The experienced writer slowly lowers the barrel (the reader, again), allowing the reader to acclimate to the depths (of the study)."': '“我们用‘作者将木桶放入井中’的比喻。初学者会将木桶（读者）直接抛入井的深处（文章中）。读者看到的只有陌生的材料。而有经验的作者则会慢慢降下木桶（再次指代读者），让读者逐步适应深度（研究的深度）。”\n> ("We use the metaphor of the writer lowering a barrel into a well. The beginning writer plunges the barrel (the reader) into the depths of the well (the article). The reader sees only unfamiliar material. The experienced writer slowly lowers the barrel (the reader, again), allowing the reader to acclimate to the depths (of the study).")',

    '"A research problem is the problem or issue that leads to the need for a study. It can originate from many potential sources. It might spring from researchers\' experiences in their personal lives or workplaces or come from debates in the literature."': '“研究问题是指导致需要开展一项研究的难题或议题。它可能源自许多潜在的来源。它可能源自研究者个人生活或工作场所的经历，也可能来自文献中的争论。”\n> ("A research problem is the problem or issue that leads to the need for a study. It can originate from many potential sources. It might spring from researchers\' experiences in their personal lives or workplaces or come from debates in the literature.")',

    '"Characteristics of a qualitative research problem are: (a) the concept is \'immature\' due to a conspicuous lack of theory and previous research; (b) a notion that the available theory may be inaccurate, inappropriate, incorrect, or biased; (c) a need exists to explore and describe the phenomena and to develop theory; or (d) the nature of the phenomenon may not be suited to quantitative measures."': '“质性研究问题的特征包括：(a)由于明显缺乏理论和先前研究，该概念还‘不成熟’；(b)认为现有的理论可能不准确、不适用、不正确或存在偏见；(c)需要探索和描述现象并发展理论；或者(d)现象的性质可能不适合量化测量。”\n> ("Characteristics of a qualitative research problem are: (a) the concept is \'immature\' due to a conspicuous lack of theory and previous research; (b) a notion that the available theory may be inaccurate, inappropriate, incorrect, or biased; (c) a need exists to explore and describe the phenomena and to develop theory; or (d) the nature of the phenomenon may not be suited to quantitative measures.")',

    '"The [[Deficiencies Model for an Introduction|deficiencies model]] of an introduction is an approach to writing an introduction to a research study that builds on gaps in the literature. It includes the elements of stating the research problem, reviewing past studies about the problem, indicating deficiencies in these studies, and advancing the significance of the study."': '“引言的[[Deficiencies Model for an Introduction|缺陷模型]]是一种撰写研究引言的方法，它建立在文献空白的基础上。它包括陈述研究问题、回顾关于该问题的既往研究、指出这些研究中的缺陷，以及提出该研究的重要性等要素。”\n> ("The [[Deficiencies Model for an Introduction|deficiencies model]] of an introduction is an approach to writing an introduction to a research study that builds on gaps in the literature. It includes the elements of stating the research problem, reviewing past studies about the problem, indicating deficiencies in these studies, and advancing the significance of the study.")',

    '"We sometimes say to our students that if they do not have a dozen references cited on the first page of their proposal, they do not have a scholarly study."': '“我们有时对学生说，如果他们在开题报告的第一页没有引用十几篇参考文献，那这就不是一项具有学术性的研究。”\n> ("We sometimes say to our students that if they do not have a dozen references cited on the first page of their proposal, they do not have a scholarly study.")',

    '"The ability to frame the study in this way separates novices from more experienced researchers. The experienced researcher has reviewed and understands topics or problems in the [[Champ|field]]. This knowledge comes from years of experience following the development of problems and their accompanying literature."': '“能够以这种方式为研究建立框架，区分了新手和经验丰富的研究者。有经验的研究者已经回顾并理解了[[Champ|该领域]]的主题或问题。这种知识来自于多年跟踪问题及其伴随文献发展的经验。”\n> ("The ability to frame the study in this way separates novices from more experienced researchers. The experienced researcher has reviewed and understands topics or problems in the [[Champ|field]]. This knowledge comes from years of experience following the development of problems and their accompanying literature.")',

    '"This passage is called the [[Purpose Statement]] because it conveys the overall intent of a proposed study in a sentence or several sentences. In proposals, researchers need to distinguish clearly among the purpose statement, the research problem, and the [[Research Question|research questions]]."': '“这一段落被称为[[Purpose Statement|目的陈述]]，因为它用一两句话传达了一项拟议研究的总体意图。在开题报告中，研究者需要明确区分目的陈述、研究问题和[[Research Question|具体的研究设问]]。”\n> ("This passage is called the [[Purpose Statement]] because it conveys the overall intent of a proposed study in a sentence or several sentences. In proposals, researchers need to distinguish clearly among the purpose statement, the research problem, and the [[Research Question|research questions]].")',

    '"The purpose statement sets forth the broader intent of the study. It is not the problem or issue or the research questions in the study."': '“目的陈述阐明了研究的更广泛意图。它既不是研究中的难题或议题，也不是具体的研究问题。”\n> ("The purpose statement sets forth the broader intent of the study. It is not the problem or issue or the research questions in the study.")',

    '"A qualitative purpose statement does not convey relating two or more variables or comparing two or more groups, as in quantitative research. Instead, it advances a single phenomenon, recognizing that the study may evolve into exploring relationships or comparing groups."': '“质性目的陈述不表达如量化研究中那样关联两个或更多变量或比较两个或更多群体的意图。相反，它提出了一个单一的现象，同时承认该研究可能会演变为探索关系或比较群体。”\n> ("A qualitative purpose statement does not convey relating two or more variables or comparing two or more groups, as in quantitative research. Instead, it advances a single phenomenon, recognizing that the study may evolve into exploring relationships or comparing groups.")',

    '"McCracken (1988) referred to the need in qualitative interviews to let the respondents describe their experiences. Interviewers (or purpose statement writers) can violate easily the \'[[Nondirectional Language|law of nondirection]]\' (McCracken, 1988, p. 21) in qualitative research by using words that suggest a directional orientation."': '“McCracken (1988) 提到在质性访谈中需要让受访者描述他们的经历。访谈者（或目的陈述写作者）如果使用暗示方向性倾向的词语，就很容易违反质性研究中的‘[[Nondirectional Language|非方向性法则]]’ (McCracken, 1988, p. 21)。”\n> ("McCracken (1988) referred to the need in qualitative interviews to let the respondents describe their experiences. Interviewers (or purpose statement writers) can violate easily the \'[[Nondirectional Language|law of nondirection]]\' (McCracken, 1988, p. 21) in qualitative research by using words that suggest a directional orientation.")',

    '"Consistent with the rhetoric of qualitative research, view this definition as not fixed but tentative and evolving throughout a study based on information from participants."': '“与质性研究的话语方式相一致，应将该定义视为非固定不变的，而是尝试性的，并且在整个研究过程中会根据参与者的信息不断演变。”\n> ("Consistent with the rhetoric of qualitative research, view this definition as not fixed but tentative and evolving throughout a study based on information from participants.")',

    '"A script contains the major words and ideas of a statement and provides space for researchers to insert their project information."': '“脚本包含了一份陈述的主要词汇和观点，并为研究者插入其项目信息留出了空间。”\n> ("A script contains the major words and ideas of a statement and provides space for researchers to insert their project information.")',

    '"The purpose of this _____ (qualitative study or more specifically a qualitative approach, such as [[Ethnography]], [[Case Study]], or other type) study is (was? will be?) to _____ (understand? explore? develop? generate? discover?) the _____ ([[Central Phenomenon]] being studied) for _____ (the participants, such as individuals, groups, or organizations) at _____ (research site). At this stage in the research, the _____ (central phenomenon being studied) will be generally defined as _____ (provide a general definition)."': '“本____（质性研究，或更具体地指明一种质性路径，如[[Ethnography|民族志]]、[[Case Study|案例研究]]或其他类型）研究的目的是（将是？）去____（理解？探索？发展？生成？发现？）在____（研究场所）的____（参与者，如个人、群体或组织）的____（被研究的[[Central Phenomenon|核心现象]]）。在研究的现阶段，____（被研究的核心现象）将被一般性地定义为____（提供一个一般性定义）。”\n> ("The purpose of this _____ (qualitative study or more specifically a qualitative approach, such as [[Ethnography]], [[Case Study]], or other type) study is (was? will be?) to _____ (understand? explore? develop? generate? discover?) the _____ ([[Central Phenomenon]] being studied) for _____ (the participants, such as individuals, groups, or organizations) at _____ (research site). At this stage in the research, the _____ (central phenomenon being studied) will be generally defined as _____ (provide a general definition).")',

    '"The purpose of this _________ (experiment? survey?) study is (was? will be?) to test the theory of _________ that __________ (explains, predicts) that the _________ (independent variable) _________ (compares? relates?) to __________ (dependent variable)."': '“本____（实验？调查？）研究的目的是（将是？）检验____的理论，该理论____（解释、预测）____（自变量）与____（因变量）相____（比较？关联？）。”\n> ("The purpose of this _________ (experiment? survey?) study is (was? will be?) to test the theory of _________ that __________ (explains, predicts) that the _________ (independent variable) _________ (compares? relates?) to __________ (dependent variable).")',

    '"Investigators place signposts to carry the reader through a plan for a study. The first signpost is the purpose statement, which establishes the central intent for the study. The next are the research questions or [[Hypothesis|hypotheses]] narrowing the purpose statement to predictions about what will be learned or questions to be answered in the study."': '“研究者通过放置‘路标’来引导读者阅读研究计划。第一个路标是目的陈述，它确立了研究的中心意图。接下来是研究问题或[[Hypothesis|假设]]，它们将目的陈述缩小为对将要学到什么的预测或研究中需要回答的问题。”\n> ("Investigators place signposts to carry the reader through a plan for a study. The first signpost is the purpose statement, which establishes the central intent for the study. The next are the research questions or [[Hypothesis|hypotheses]] narrowing the purpose statement to predictions about what will be learned or questions to be answered in the study.")',

    '"The most rigorous form of quantitative research follows from a test of a theory and the specification of research questions or hypotheses that logically follow or challenge the theory."': '“最严格形式的量化研究源于对某一理论的检验，以及对逻辑上遵循或挑战该理论的研究问题或假设的详细说明。”\n> ("The most rigorous form of quantitative research follows from a test of a theory and the specification of research questions or hypotheses that logically follow or challenge the theory.")',

    '"A [[Null Hypothesis]] makes a prediction that in the general population, no relationship or no significant difference exists between groups on a variable. The intent is to disprove a theory by stating a negative expectation. The wording is, \'There is no difference (or relationship)\' between the groups."': '“[[Null Hypothesis|零假设]]做出这样一种预测：在总体中，变量间不存在关系，或者群体之间不存在显著差异。其意图是通过陈述否定性的预期来反驳某项理论。其表述方式为群体之间‘没有差异（或关系）’。”\n> ("A [[Null Hypothesis]] makes a prediction that in the general population, no relationship or no significant difference exists between groups on a variable. The intent is to disprove a theory by stating a negative expectation. The wording is, \'There is no difference (or relationship)\' between the groups.")',

    '"An [[Alternative Hypothesis]] makes a prediction about a significant relationship between variables. Moreover, it is important to make this alternative hypothesis directional, such that it is a prediction in a certain direction."': '“[[Alternative Hypothesis|备择假设]]对变量之间的显著关系做出预测。此外，重要的是使这种备择假设具有方向性，即它是在某个特定方向上的预测。”\n> ("An [[Alternative Hypothesis]] makes a prediction about a significant relationship between variables. Moreover, it is important to make this alternative hypothesis directional, such that it is a prediction in a certain direction.")',

    '"In qualitative research, the intent is to explore the general, complex set of factors surrounding the central phenomenon and present the broad, varied perspectives or meanings that participants hold."': '“在质性研究中，其意图是探索围绕核心现象的普遍而复杂的一组因素，并呈现参与者所持有的广泛、多样的观点或意义。”\n> ("In qualitative research, the intent is to explore the general, complex set of factors surrounding the central phenomenon and present the broad, varied perspectives or meanings that participants hold.")',

    '"Begin the research questions with the words what or how to convey an open and emerging design. The word why often implies that the researcher is trying to explain why something occurs, and this suggests to us probable cause-and-effect thinking associated with quantitative research and that limits the explanations rather than opening them up for participant views."': '“用what或how这两个词作为研究问题的开头，以传达一种开放且不断涌现的设计。why这个词通常暗示研究者试图解释某事为何发生，这向我们表明了与量化研究相关的可能的因果思维，并且这种思维限制了解释，而不是为参与者的观点敞开大门。”\n> ("Begin the research questions with the words what or how to convey an open and emerging design. The word why often implies that the researcher is trying to explain why something occurs, and this suggests to us probable cause-and-effect thinking associated with quantitative research and that limits the explanations rather than opening them up for participant views.")',

    '"We often ask, \'What is the one single concept that you want to explore?\'"': '“我们经常会问：‘你想要探索的那唯一一个单一概念是什么？’”\n> ("We often ask, \'What is the one single concept that you want to explore?\'")',

    '"Expect the research questions to evolve and change during the study. Often in qualitative studies, the questions are under continual review and reformulation (as in a grounded theory study). This approach may be problematic for individuals accustomed to quantitative designs in which the research questions remain fixed and never change throughout the study."': '“要预见到研究问题在研究期间会演变和改变。在质性研究中，问题往往处于持续的审查和重新构思之中（正如在扎根理论研究中那样）。对于习惯于量化设计的个体来说，这种方法可能会造成困扰，因为在量化设计中，研究问题保持固定并在整个研究过程中从不改变。”\n> ("Expect the research questions to evolve and change during the study. Often in qualitative studies, the questions are under continual review and reformulation (as in a grounded theory study). This approach may be problematic for individuals accustomed to quantitative designs in which the research questions remain fixed and never change throughout the study.")',

    '"A [[Mixed Methods Question]] is a methods question, and a question asking about the learning from integration. Integration is a central component of mixed methods."': '“[[Mixed Methods Question|混合方法研究问题]]是一个方法问题，也是一个询问从整合中能学到什么的问题。整合是混合方法的核心组成部分。”\n> ("A [[Mixed Methods Question]] is a methods question, and a question asking about the learning from integration. Integration is a central component of mixed methods.")',

    '"These questions or hypotheses can be advanced at the beginning or emerge during a later phase of the research. For example, if the study begins with a quantitative phase, the investigator might introduce [[Hypothesis|hypotheses]]. Later in the study, when the qualitative phase is addressed, the qualitative research questions appear."': '“这些问题或假设可以在研究开始时提出，也可以在研究的后期阶段涌现出来。例如，如果研究以量化阶段开始，研究者可能会引入[[Hypothesis|假设]]。在研究的后期阶段，当处理到质性阶段时，质性研究问题就会出现。”\n> ("These questions or hypotheses can be advanced at the beginning or emerge during a later phase of the research. For example, if the study begins with a quantitative phase, the investigator might introduce [[Hypothesis|hypotheses]]. Later in the study, when the qualitative phase is addressed, the qualitative research questions appear.")',

    '"In a single-phase mixed methods project (a [[Convergent Design]]) in which the quantitative and qualitative results are merged, either the quantitative or the qualitative questions can be posed first. In a two-phase project (an [[Explanatory Sequential Design]]), the first-phase quantitative questions or hypotheses would come first, followed by the second-phase qualitative questions."': '“在一个合并量化和质性结果的单阶段混合方法项目（[[Convergent Design|聚敛式设计]]）中，量化问题或质性问题都可以首先提出。在一个分为两阶段的项目（[[Explanatory Sequential Design|解释性序列设计]]）中，第一阶段的量化问题或假设将最先出现，随后是第二阶段的质性问题。”\n> ("In a single-phase mixed methods project (a [[Convergent Design]]) in which the quantitative and qualitative results are merged, either the quantitative or the qualitative questions can be posed first. In a two-phase project (an [[Explanatory Sequential Design]]), the first-phase quantitative questions or hypotheses would come first, followed by the second-phase qualitative questions.")',

    '"We encourage mixed methods researchers to write quantitative, qualitative, and a mixed methods question into their studies. By adding a mixed methods question, the researcher conveys the importance of integrating or combining the quantitative and qualitative elements."': '“我们鼓励混合方法研究者将量化、质性以及一个混合方法研究问题写入他们的研究中。通过添加一个混合方法研究问题，研究者传达了整合或组合量化与质性要素的重要性。”\n> ("We encourage mixed methods researchers to write quantitative, qualitative, and a mixed methods question into their studies. By adding a mixed methods question, the researcher conveys the importance of integrating or combining the quantitative and qualitative elements.")',

    '"An ideal format would be to write the three types of questions into separate sections, such as the quantitative questions or hypotheses, the qualitative questions, and the mixed methods question."': '“一种理想的格式是将这三种类型的问题分别写在不同的部分，例如量化问题或假设部分、质性问题部分，以及混合方法问题部分。”\n> ("An ideal format would be to write the three types of questions into separate sections, such as the quantitative questions or hypotheses, the qualitative questions, and the mixed methods question.")'
}

for eng, translated in translations.items():
    content = content.replace(eng, translated)

with open(path, 'w', encoding='utf-8') as f:
    f.write(content)
