import os

replacements = {
    '"An [[Randomised Controlled Trials|RCT]] by itself is insufficient to meet the needs of policy or practice decision makers."': '“单靠[[Randomised Controlled Trials|RCT（随机对照试验）]]不足以满足政策或实践决策者的需求。”\n> ("An [[Randomised Controlled Trials|RCT]] by itself is insufficient to meet the needs of policy or practice decision makers.")',
    '"Local knowledge... may be essential to growing and sustaining school improvement efforts."': '“本地知识……对于发展和维持学校改进工作可能是必不可少的。”\n> ("Local knowledge... may be essential to growing and sustaining school improvement efforts.")',
    '"We are pushed to be teachers as researchers, when really we should be teachers as scholars."': '“我们被推着去成为作为研究者的教师，而实际上我们应该成为作为学者的教师。”\n> ("We are pushed to be teachers as researchers, when really we should be teachers as scholars.")',
    '"Use [the EEF Toolkit] not as guidance, but as a way of asking questions."': '“不要将 [EEF工具包] 作为指导，而是作为提出问题的一种方式。”\n> ("Use [the EEF Toolkit] not as guidance, but as a way of asking questions.")',
    '"Fluidity, not fidelity"': '“流动性，而非忠实度”\n> ("Fluidity, not fidelity")',
    
    '"The analysis in this report documents how an increased presence of private sector actors is reshaping the ways in which state schooling policy is developed and enacted in classrooms, staffrooms, schools and local communities."': '“本报告中的分析记录了私营部门参与者日益增加的存在感，是如何重塑公立学校政策在课堂、教职员室、学校和当地社区中制定与颁布的方式的。”\n> ("The analysis in this report documents how an increased presence of private sector actors is reshaping the ways in which state schooling policy is developed and enacted in classrooms, staffrooms, schools and local communities.")',
    
    '"In short, the importance of meta-analysis for estimating causal effects has been grossly overrated. A conventional [[Literature Review]] will often do better."': '“简而言之，元分析对于估计因果效应的重要性被严重高估了。传统的[[Literature Review|文献综述]]通常会做得更好。”\n> ("In short, the importance of meta-analysis for estimating causal effects has been grossly overrated. A conventional [[Literature Review]] will often do better.")',
    '"For every well done and useful study there is at least one other doing what under the famous Daubert ruling would be called junk science."': '“对于每一项做得好且有用的研究，至少存在另一项研究在做著名的道伯特裁决（Daubert ruling）所称的垃圾科学。”\n> ("For every well done and useful study there is at least one other doing what under the famous Daubert ruling would be called junk science.")',
    '"It is sometimes difficult to determine which is which. Some purveyors of junk do not know what they are doing but proceed with all of the superficial trappings of high-quality work. Other purveyors of junk know well what they are doing and use those same trappings to cover their tracks."': '“有时很难分辨孰是孰非。一些垃圾科学的兜售者不知道自己在做什么，却带着高质量工作的所有表面特征继续前进。另一些兜售者则清楚地知道自己在做什么，并利用同样的特征来掩盖他们的踪迹。”\n> ("It is sometimes difficult to determine which is which. Some purveyors of junk do not know what they are doing but proceed with all of the superficial trappings of high-quality work. Other purveyors of junk know well what they are doing and use those same trappings to cover their tracks.")',
    '"There can be one causal effect for each possible shuffling of the study units, and a single causal effect no longer exists."': '“对于研究单位的每一种可能重组，都可以产生一个因果效应，于是单一的因果效应也就不复存在了。”\n> ("There can be one causal effect for each possible shuffling of the study units, and a single causal effect no longer exists.")',
    '"The benchmark for any evaluation is current knowledge, not perfection. Hence, designs with less internal validity than randomized experiments can sometimes be probative."': '“任何评估的基准都是现有的知识，而不是完美。因此，内部效度低于随机实验的设计有时也具有证明力。”\n> ("The benchmark for any evaluation is current knowledge, not perfection. Hence, designs with less internal validity than randomized experiments can sometimes be probative.")',
    '"The importance of [[Meta-analysis]] for estimating causal effects has been grossly overrated. A conventional [[Literature Review]] will often do better."': '“[[Meta-analysis|元分析]]对于估计因果效应的重要性被严重高估了。传统的[[Literature Review|文献综述]]通常会做得更好。”\n> ("The importance of [[Meta-analysis]] for estimating causal effects has been grossly overrated. A conventional [[Literature Review]] will often do better.")',
    
    '"Fundamental to our book is the notion that strength and impact are developed not solely through relationships between universities and industry but engagement, in research and scholarship, education and learning, and public benefits."': '“贯穿本书的基本理念是：实力与影响力的发展，不仅仅依靠大学与产业之间的关系，更在于研究与学术、教育与学习以及公共利益方面的深度参与。”\n> ("Fundamental to our book is the notion that strength and impact are developed not solely through relationships between universities and industry but engagement, in research and scholarship, education and learning, and public benefits.")',
    
    '"Why would they be kind and respectful toward those who are seen as, and probably are, the very cause of their downgrading?"': '“他们为什么要对那些被视为、且很可能就是导致他们地位下降原因的人友善和尊重呢？”\n> ("Why would they be kind and respectful toward those who are seen as, and probably are, the very cause of their downgrading?")',
    
    '"Perhaps the most significant challenge is the continuity and continuation of collaborative interactions between a company and university when the individuals who are key to the relationship switch to different jobs or different job descriptions."': '“也许最重大的挑战在于，当对关系至关重要的个体调换工作或岗位职责发生变化时，企业与大学之间合作互动的连续性和延续性。”\n> ("Perhaps the most significant challenge is the continuity and continuation of collaborative interactions between a company and university when the individuals who are key to the relationship switch to different jobs or different job descriptions.")',
    '"Ask the question, what are the launch members spending money on independently that could be addressed with a shared investment? The answer to this question is the \'pain\' in industry and a potential research theme for the consortium."': '“问这样一个问题：发起成员目前分别在独立花费哪些资金，而这些是可以通过共享投资来解决的？这个问题的答案就是产业的‘痛点’，也是该联盟的潜在研究主题。”\n> ("Ask the question, what are the launch members spending money on independently that could be addressed with a shared investment? The answer to this question is the \'pain\' in industry and a potential research theme for the consortium.")',
    '"It may seem like an impossible task to get competitors to work together in a consortium [[Tracking|setting]], but experience shows that it is possible if the right conditions are established."': '“让竞争对手在一个联盟[[Tracking|环境]]中合作似乎是一项不可能完成的任务，但经验表明，如果建立起适当的条件，这是可能实现的。”\n> ("It may seem like an impossible task to get competitors to work together in a consortium [[Tracking|setting]], but experience shows that it is possible if the right conditions are established.")',
    
    '"One problem is that most frameworks for analyzing transfer take the \'borrowed\' policy as the focal point. This contributes to a myopic view of transfer and conceals the role of context."': '“一个问题在于，大多数分析转移的框架都以‘借用’的政策为焦点。这导致了对转移的短视观点，并掩盖了情境的作用。”\n> ("One problem is that most frameworks for analyzing transfer take the \'borrowed\' policy as the focal point. This contributes to a myopic view of transfer and conceals the role of context.")',
    '"Education reform is not science, but a highly normative endeavour – perhaps the premier arena for social discourse on values."': '“教育改革不是科学，而是一项高度规范性的努力——也许是进行价值观社会话语的首要舞台。”\n> ("Education reform is not science, but a highly normative endeavour – perhaps the premier arena for social discourse on values.")',
    '"Externalizations \'filter\' the reception and description of an international environment according to the changing problem configurations and reflection situations internal to a given system."': '“外部化根据特定系统内部不断变化的问题配置和反思情境，来‘过滤’对国际环境的接收和描述。”\n> ("Externalizations \'filter\' the reception and description of an international environment according to the changing problem configurations and reflection situations internal to a given system.")',
    '"The \'[[Cross-National Attraction]]\' stage ... is of particular importance because it initiates the entire policy-borrowing cycle."': '“‘[[Cross-National Attraction|跨国吸引力]]’阶段……特别重要，因为它启动了整个政策借用周期。”\n> ("The \'[[Cross-National Attraction]]\' stage ... is of particular importance because it initiates the entire policy-borrowing cycle.")',
    '"If we as comparativists do not make the connection between our research, transfer processes, and the home context explicit someone less knowledgeable will."': '“如果我们作为比较学者不将我们的研究、转移过程与本土情境之间的联系明确化，那么那些知识较少的人就会代劳。”\n> ("If we as comparativists do not make the connection between our research, transfer processes, and the home context explicit someone less knowledgeable will.")',
    
    '"Engagement is less organizationally embedded than commercialization, and is more autonomously driven by individuals."': '“相较于商业化，‘参与（Engagement）’在组织上的嵌入程度较低，且更多地由个体自主驱动。”\n> ("Engagement is less organizationally embedded than commercialization, and is more autonomously driven by individuals.")',
    '"UI collaborations are likely to be plagued with conflicts due to a weak attitudinal alignment between partners."': '“由于合作伙伴之间的态度契合度较弱，产学（UI）合作很可能会受到冲突的困扰。”\n> ("UI collaborations are likely to be plagued with conflicts due to a weak attitudinal alignment between partners.")',
    '"Embrace industry engagement as part of core ethos. ... Operationally, translate industry or customer requirements into programs with the authority and charge for sustained delivery."': '“将产业参与作为核心理念的一部分。……在操作上，将产业或客户需求转化为具有持续交付权责的项目。”\n> ("Embrace industry engagement as part of core ethos. ... Operationally, translate industry or customer requirements into programs with the authority and charge for sustained delivery.")',
    '"Flexible IP policies. University Partnership Managers who can make the process of understanding the universities research capabilities easier. University Partnership Managers specialized in my industry, to know what they need to know about working with us."': '“灵活的知识产权（IP）政策。能让理解大学研究能力的过程变得更轻松的大学合作经理。专门针对我所在行业的大学合作经理，他们需要了解在与我们合作时必须知道的知识。”\n> ("Flexible IP policies. University Partnership Managers who can make the process of understanding the universities research capabilities easier. University Partnership Managers specialized in my industry, to know what they need to know about working with us.")',
    
    '"The identification of the \'[[Promising Student]]\' is not simply a matter of finding the naturally given talents, however. Rather, it means to address students with respect to their potential success through self-evaluation and self-optimization."': '“然而，‘[[Promising Student|有前途的学生]]’的识别并非仅仅是寻找天生的才华。相反，这意味着要通过自我评价和自我优化，着眼于学生的潜在成功来对待他们。”\n> ("The identification of the \'[[Promising Student]]\' is not simply a matter of finding the naturally given talents, however. Rather, it means to address students with respect to their potential success through self-evaluation and self-optimization.")',
    '"The current approaches lack the fundamental idea within (higher) education that education and [[Bildung]] are related to an open and unpredictable future; they go beyond the correlations of data."': '“当前的方法缺乏（高等）教育中的一个基本理念，即教育和 [[Bildung|陶冶（Bildung）]] 是与开放和不可预测的未来相关的；它们超越了数据的相关性。”\n> ("The current approaches lack the fundamental idea within (higher) education that education and [[Bildung]] are related to an open and unpredictable future; they go beyond the correlations of data.")',
    '"The exercise of critique is a crucial knowledge practice within the course of study that reopens what is there to think and to explore."': '“批判的实践是学习过程中一项至关重要的知识实践，它重新开启了有哪些事物需要思考和探索。”\n> ("The exercise of critique is a crucial knowledge practice within the course of study that reopens what is there to think and to explore.")',
    
    '"If the ultimate purpose of a [[Innovation Hub|research park]] or an innovation center is to raise the standard of living through increased commercial activity and entrepreneurship, then university and industry partners can draw from these approaches to make location-specific decisions to create mutually beneficial and positively reinforcing ecosystems."': '“如果[[Innovation Hub|研究园区]]或创新中心的最终目的是通过增加商业活动和创业精神来提高生活水平，那么大学和产业合作伙伴就可以利用这些方法做出针对特定地点的决策，以创建互惠互利和正向强化的生态系统。”\n> ("If the ultimate purpose of a [[Innovation Hub|research park]] or an innovation center is to raise the standard of living through increased commercial activity and entrepreneurship, then university and industry partners can draw from these approaches to make location-specific decisions to create mutually beneficial and positively reinforcing ecosystems.")',
    '"Density is destiny."': '“密度即命运。”\n> ("Density is destiny.")',
    
    '"The fundamentals of academic critique are that it relates to the idea not the person; takes careful consideration of the tenets and assumptions; and is aimed at informing and extending the debate – not shutting it down because the ideas are not welcome or are not part of some critics\' dogma."': '“学术批判的基本原则是：它针对的是思想而非个人；仔细考量那些原则和假设；目的是为辩论提供信息并加以扩展——而不是因为思想不受欢迎或不符合某些批评者的教条就试图将其扼杀。”\n> ("The fundamentals of academic critique are that it relates to the idea not the person; takes careful consideration of the tenets and assumptions; and is aimed at informing and extending the debate – not shutting it down because the ideas are not welcome or are not part of some critics\' dogma.")',
    '"It is my belief that it is important for academics to speak out on topics within their expertise and take seriously their role as critics and conscience of society."': '“我相信，学者们就其专业领域内的话题发声，并认真对待他们作为社会批评家和良知的角色，是非常重要的。”\n> ("It is my belief that it is important for academics to speak out on topics within their expertise and take seriously their role as critics and conscience of society.")',
    '"Being part of the solution is a lot harder than critiquing from the side – and both views, in my opinion, are critical to a worthwhile society."': '“成为解决方案的一部分比在旁指手画脚要困难得多——而在我看来，这两种观点对于一个有价值的社会来说都是至关重要的。”\n> ("Being part of the solution is a lot harder than critiquing from the side – and both views, in my opinion, are critical to a worthwhile society.")',
    '"Providing black and white answers is not the nature of academic critique."': '“提供非黑即白的答案并非学术批判的本质。”\n> ("Providing black and white answers is not the nature of academic critique.")',
    
    '"Why is it that educational research so rarely has an impact on the practice of education?"': '“为什么教育研究如此罕见地对教育实践产生影响？”\n> ("Why is it that educational research so rarely has an impact on the practice of education?")',
    '"This definition does not refer to simply disseminating information about generic principles of effective practice, which has not generally been found to make much of a difference in practices or outcomes."': '“该定义并非仅仅指传播关于有效实践的一般原则的信息，通常发现这种做法对实践或结果并不能产生多大影响。”\n> ("This definition does not refer to simply disseminating information about generic principles of effective practice, which has not generally been found to make much of a difference in practices or outcomes.")',
    '"The design should be appropriate to the question being asked. ... When we want to know \'what works,\' we must ask, \'Compared to what?\'"': '“设计应该与所提出的问题相适应。……当我们想知道‘什么有效’时，我们必须问，‘与什么相比？’”\n> ("The design should be appropriate to the question being asked. ... When we want to know \'what works,\' we must ask, \'Compared to what?\'")',
    '"The winners in this would be millions of children, especially those who are least well served by the current system."': '“其中的赢家将是数以百万计的儿童，特别是那些在当前体系中服务最不到位的儿童。”\n> ("The winners in this would be millions of children, especially those who are least well served by the current system.")',
    '"Programs with a strong evidence base that are implemented as they were in the validating research are likely to produce better outcomes for children."': '“具备坚实证据基础且能像在验证研究中那样被实施的项目，很可能为儿童产生更好的结果。”\n> ("Programs with a strong evidence base that are implemented as they were in the validating research are likely to produce better outcomes for children.")',
    
    '"any UI relationship that aims to become a [[Strategic Partnership]] will be built on trust between partners, mutually beneficial goals, consistent points of contact, strategic roadmapping, long-term planning, [[Tracking|setting]] and accounting of annual objectives, and adjusting, pivoting, and growing."': '“任何旨在成为[[Strategic Partnership|战略伙伴关系]]的产学（UI）关系，都将建立在伙伴间的信任、互利的目标、一致的联系点、战略路线图、长期规划、年度目标的[[Tracking|设定]]与核算，以及不断调整、转向和成长之上。”\n> ("any UI relationship that aims to become a [[Strategic Partnership]] will be built on trust between partners, mutually beneficial goals, consistent points of contact, strategic roadmapping, long-term planning, [[Tracking|setting]] and accounting of annual objectives, and adjusting, pivoting, and growing.")',
    '"there is no single solution or tool that provides perfect technological alignment. Instead the most efficient and effective approach to identify intersecting interests of the university and the company is the use of a variety of technology platforms, databases, and websites in combination with the human insights (that of university corporate engagement professionals, technology licensing officers, as well as deans and department chairs)."': '“没有单一的解决方案或工具能够提供完美的技术对齐。相反，识别大学与企业利益交叉点的最高效、最有效的方法，是将各种技术平台、数据库和网站与人类洞察力（即大学企业参与专业人员、技术许可专员以及院长和系主任的洞察力）结合使用。”\n> ("there is no single solution or tool that provides perfect technological alignment. Instead the most efficient and effective approach to identify intersecting interests of the university and the company is the use of a variety of technology platforms, databases, and websites in combination with the human insights (that of university corporate engagement professionals, technology licensing officers, as well as deans and department chairs).")',
    '"you know one company or university, you know only one company or university."': '“如果你只了解一家企业或一所大学，那么你真的只是了解了那一家企业或一所大学而已。”\n> ("you know one company or university, you know only one company or university.")',
    
    '"Evidence does not supply us with rules for action but only with [[Hypothesis|hypotheses]] for intelligent problem solving, and for making inquiries about our ends in education."': '“证据并不为我们提供行动规则，而仅仅为我们提供了用于智能解决问题的[[Hypothesis|假设]]，以及用于质询我们教育目的的假设。”\n> ("Evidence does not supply us with rules for action but only with [[Hypothesis|hypotheses]] for intelligent problem solving, and for making inquiries about our ends in education.")',
    '"There is something quite dangerous about the use of [[Quantitative Research]] for propaganda purposes."': '“将[[Quantitative Research|量化研究]]用于宣传目的有着极大的危险性。”\n> ("There is something quite dangerous about the use of [[Quantitative Research]] for propaganda purposes.")',
    '"School leaders and teachers need to create school, staffroom, and classroom environments where error is welcome as a learning opportunity."': '“学校领导和教师需要创造出在学校、教职员室和课堂中都将错误视为学习机会而受欢迎的环境。”\n> ("School leaders and teachers need to create school, staffroom, and classroom environments where error is welcome as a learning opportunity.")',
    
    '"rankings have become an inevitable outcome and metaphor for the geopolitics of HE. Because they predominantly measure basic research and dissemination — in limited fields and in a traditional way — they provide competitive advantage to elite universities and nations which benefit from accumulated public and/or private wealth and investment over decades if not centuries. They reflect the structure of the world economy and global science."': '“排名已成为高等教育地缘政治不可避免的结果与隐喻。因为它们主要测量基础研究和传播——在有限的领域且以传统的方式——它们为那些得益于数十甚至数百年来积累的公共和/私人财富与投资的精英大学和国家提供了竞争优势。它们反映了世界经济和全球科学的结构。”\n> ("rankings have become an inevitable outcome and metaphor for the geopolitics of HE. Because they predominantly measure basic research and dissemination — in limited fields and in a traditional way — they provide competitive advantage to elite universities and nations which benefit from accumulated public and/or private wealth and investment over decades if not centuries. They reflect the structure of the world economy and global science.")',
    '"prestige is to higher education what profit is to corporations"': '“声望之于高等教育，犹如利润之于企业。”\n> ("prestige is to higher education what profit is to corporations")',
    '"Ranking reinforces the advantages enjoyed by leading universities. It celebrates their status and propels more money and talent towards them, helping them to stay on top. It is difficult for outsiders, emerging universities and countries to break in. Rankings are not \'fair\' to competing universities. The starting positions are manifestly unequal."': '“排名强化了领先大学所享有的优势。它庆祝它们的地位，并推动更多的资金和人才流向它们，帮助它们保持领先。局外人、新兴大学和国家很难打破这一局面。排名对于竞争的大学来说并不‘公平’。它们的起跑线显然是不平等的。”\n> ("Ranking reinforces the advantages enjoyed by leading universities. It celebrates their status and propels more money and talent towards them, helping them to stay on top. It is difficult for outsiders, emerging universities and countries to break in. Rankings are not \'fair\' to competing universities. The starting positions are manifestly unequal.")',
    '"a formidable machinery of symbolic and economic power… a politico-ideological technology that serves not the educational needs of students or teachers, but rather the interests of the global elite"': '“一部强大的符号和经济权力机器……一种政治意识形态技术，它服务的不是学生或教师的教育需求，而是全球精英的利益。”\n> ("a formidable machinery of symbolic and economic power… a politico-ideological technology that serves not the educational needs of students or teachers, but rather the interests of the global elite")',
    
    '"the [[Meta-analysis]] evidence on the quality of teaching has no demonstrable relevance to schooling policy. Moreover, taken literally, it would mean that the Minister and officials assert that achievement should be raised by asking school students to rate their teachers, which is incoherent."': '“关于教学质量的[[Meta-analysis|元分析]]证据与学校政策没有可证实的关联。此外，如果按字面理解，这意味着部长和官员们断言应该通过让在校学生对他们的教师进行评级来提高学业成就，这是不合逻辑的。”\n> ("the [[Meta-analysis]] evidence on the quality of teaching has no demonstrable relevance to schooling policy. Moreover, taken literally, it would mean that the Minister and officials assert that achievement should be raised by asking school students to rate their teachers, which is incoherent.")',
    '"an expression becomes a slogan \'when it is used to produce a thoughtless knee-jerk reaction of agreement or disagreement simply on the basis of the [[Familiarization|familiarity]] of the words rather than on the basis of reason\' (Kreeft, 2010, p. 78)"': '“当一种表达‘被用来仅仅基于词语的[[Familiarization|熟悉度]]而非理性，去产生不假思索的、膝跳反射般的同意或不同意反应时’，它就成了一个口号 (Kreeft, 2010, p. 78)。”\n> ("an expression becomes a slogan \'when it is used to produce a thoughtless knee-jerk reaction of agreement or disagreement simply on the basis of the [[Familiarization|familiarity]] of the words rather than on the basis of reason\' (Kreeft, 2010, p. 78)")',
    '"the positive sign of the average [[Effect Size]] suggests that increasing [[Class Size]] is poor policy ([[John Hattie|Hattie]], 2009a, p. 88)"': '“平均[[Effect Size|效应量]]的正号表明，增加[[Class Size|班级规模]]是一项糟糕的政策（[[John Hattie|Hattie]], 2009a, p. 88）。”\n> ("the positive sign of the average [[Effect Size]] suggests that increasing [[Class Size]] is poor policy ([[John Hattie|Hattie]], 2009a, p. 88)")',
    '"researchers have a particular responsibility to be watchful both for material fallacies and their mistaken use by policy actors, and on the other hand, they must be prepared to interrupt and challenge flawed public education policy debates whenever they occur."': '“研究者有一种特殊的责任：一方面要警惕实质性谬误以及政策参与者对其的错误使用；另一方面，当有缺陷的公共教育政策辩论发生时，他们必须准备好随时打断并挑战它。”\n> ("researchers have a particular responsibility to be watchful both for material fallacies and their mistaken use by policy actors, and on the other hand, they must be prepared to interrupt and challenge flawed public education policy debates whenever they occur.")',
    
    '"Innovation processes were \'neither smooth nor linear, nor often well behaved\'."': '“创新过程‘既不平滑也不线性，而且通常表现得不太规矩’。”\n> ("Innovation processes were \'neither smooth nor linear, nor often well behaved\'.")',
    
    '"The education academic in the role of [[Critic and Conscience of Society]] has an obligation to include non-school factors in all analyses of differential educational achievement because otherwise both politicians and citizens are encouraged to believe that changes in educational arrangements alone can solve much of the existing inequalities in educational achievements."': '“扮演[[Critic and Conscience of Society|社会批评家与良知]]角色的教育学者有义务在所有关于不同学业成就的分析中纳入非学校因素，因为否则政治家和公民都会受到鼓动去相信：单靠改变教育安排就能解决很大一部分现有的教育成就中的不平等。”\n> ("The education academic in the role of [[Critic and Conscience of Society]] has an obligation to include non-school factors in all analyses of differential educational achievement because otherwise both politicians and citizens are encouraged to believe that changes in educational arrangements alone can solve much of the existing inequalities in educational achievements.")',
    '"This reductionist and naive view of the influence of schooling alone in determining educational achievements is very convenient for politicians and policy makers because it diverts attention away from more fundamental questions about social and economic inequalities in society."': '“这种认为单靠学校教育就能决定学业成就的还原论和幼稚观点，对政治家和政策制定者来说非常方便，因为它将人们的注意力从关于社会中社会和经济不平等的更根本问题上转移开了。”\n> ("This reductionist and naive view of the influence of schooling alone in determining educational achievements is very convenient for politicians and policy makers because it diverts attention away from more fundamental questions about social and economic inequalities in society.")',
    '"In this role, Bernstein was acting as a critic and conscience of society: that is, he drew attention to the crucial importance of non-school factors."': '“在这个角色中，Bernstein 是在扮演社会批评家和良知的角色：即，他唤起了人们对非学校因素至关重要性的关注。”\n> ("In this role, Bernstein was acting as a critic and conscience of society: that is, he drew attention to the crucial importance of non-school factors.")',
    
    '"Technical rationality is the heritage of Positivism, the powerful philosophical doctrine that grew up in the nineteenth century as an account of the rise of science and technology and as a social movement aimed at applying the achievements of science and technology to the well-being of mankind."': '“技术理性是实证主义的遗产，这一强大的哲学学说在十九世纪成长起来，既作为对科学技术崛起的解释，也作为一场旨在将科学技术的成就应用于人类福祉的社会运动。”\n> ("Technical rationality is the heritage of Positivism, the powerful philosophical doctrine that grew up in the nineteenth century as an account of the rise of science and technology and as a social movement aimed at applying the achievements of science and technology to the well-being of mankind.")',
    '"In Hattie\'s theory of [[Visible Learning]], the teachers must, with [[Feedback]], feed-up and forward, create an environment in which the students... direct the students\' activities toward already formulated learning objectives. It is a closed system in which the learning objective sanctifies the means of teaching."': '“在 Hattie 的[[Visible Learning|可见的学习]]理论中，教师必须利用[[Feedback|反馈]]（向后反馈、向上反馈和向前反馈），创造一个环境，在其中学生……将学生的活动引向已经制定好的学习目标。这是一个封闭的系统，其中学习目标使教学手段变得神圣化。”\n> ("In Hattie\'s theory of [[Visible Learning]], the teachers must, with [[Feedback]], feed-up and forward, create an environment in which the students... direct the students\' activities toward already formulated learning objectives. It is a closed system in which the learning objective sanctifies the means of teaching.")',
    '"Hattie\'s theory of learning thus has \'the ideological function of making the technical approach to learning self-evident and dominant\'"': '“因此，Hattie 的学习理论具有‘使技术的学习途径变得不言自明且占据主导地位的意识形态功能’。”\n> ("Hattie\'s theory of learning thus has \'the ideological function of making the technical approach to learning self-evident and dominant\'")',
    '"What [[Visible Learning]] accomplishes... is to supply a theory of teaching... that directly challenges traditional understandings of the role of education."': '“[[Visible Learning|可见的学习]]所取得的成就……是提供了一种直接挑战对教育角色传统理解的……教学理论。”\n> ("What [[Visible Learning]] accomplishes... is to supply a theory of teaching... that directly challenges traditional understandings of the role of education.")',
    '"It was not the scientific discoveries or the original data produced by [[John Hattie|Hattie]] or the evidence-based movement in itself that made a difference but the promises embedded in the theory of [[Technical Rationality]] that could legitimize the educational system."': '“真正产生影响的，并非[[John Hattie|Hattie]]所做出的科学发现或原始数据，也非证据为本运动本身，而是[[Technical Rationality|技术理性]]理论中所蕴含的能够使教育系统合法化的承诺。”\n> ("It was not the scientific discoveries or the original data produced by [[John Hattie|Hattie]] or the evidence-based movement in itself that made a difference but the promises embedded in the theory of [[Technical Rationality]] that could legitimize the educational system.")',
    '"The atomization of educational effects (effect sizes) becomes, at the same time, the atomization of the students and teachers into a number of [[Variable|variables]]."': '“教育效应（效应量）的原子化，同时也就变成了将学生和教师原子化为一系列[[Variable|变量]]。”\n> ("The atomization of educational effects (effect sizes) becomes, at the same time, the atomization of the students and teachers into a number of [[Variable|variables]].")',
    '"In many respects, Hattie\'s theory of learning thus has \'the ideological function of making the technical approach to learning self-evident and dominant\' (Kvale, 1976, p. 106—our translation)."': '“在许多方面，Hattie 的学习理论因此具有‘使技术的学习途径变得不言自明且占据主导地位的意识形态功能’ (Kvale, 1976, p. 106—作者译)。”\n> ("In many respects, Hattie\'s theory of learning thus has \'the ideological function of making the technical approach to learning self-evident and dominant\' (Kvale, 1976, p. 106—our translation).")',
    
    '"For such systems, thinking is just an interfering [[Variable]] because it takes time. For an education process guided by pedagogy, however, thinking is the central action that should be cultivated in school."': '“对于此类系统而言，思考仅仅是一个干扰[[Variable|变量]]，因为它会耗费时间。然而，对于受教育学指导的教育过程而言，思考才是应该在学校中培养的核心行动。”\n> ("For such systems, thinking is just an interfering [[Variable]] because it takes time. For an education process guided by pedagogy, however, thinking is the central action that should be cultivated in school.")',
    '"In this kind of knowledge there is no linearity of time from past into future, just synchrony."': '“在这种知识中，不存在从过去到未来的时间线性，只有同步性。”\n> ("In this kind of knowledge there is no linearity of time from past into future, just synchrony.")',
    '"Insight is no longer relevant if all that is tracked and regulated is behavior. The age of reason finally comes to an end. (...) Now it seems that people do not have to be illuminated but simply regulated by points and badges in order to make them fitter, happier, and more productive."': '“如果被跟踪和调节的仅仅是行为，那么洞察力就不再相关了。理性的时代终于走向终结。（……）现在看来，人们不需要被启蒙，而只需被分数和徽章所调节，就能让他们变得更适应、更快乐、更多产。”\n> ("Insight is no longer relevant if all that is tracked and regulated is behavior. The age of reason finally comes to an end. (...) Now it seems that people do not have to be illuminated but simply regulated by points and badges in order to make them fitter, happier, and more productive.")',
    '"the \'concept of [[Bildung]] always contains an understanding of what is human (an understanding of humanity) and how we can attain this. It always implies an idea of humanity and a knowledge and representation of that which is unsatisfactory or insufficient\'"': '“‘[[Bildung|陶冶（Bildung）]]的概念总是包含着一种对什么是人的理解（对人性的理解），以及我们如何才能实现这一点。它总是蕴含着一种人性的理念，以及对那些令人不满或不充分的事物的认识和表征。’”\n> ("the \'concept of [[Bildung]] always contains an understanding of what is human (an understanding of humanity) and how we can attain this. It always implies an idea of humanity and a knowledge and representation of that which is unsatisfactory or insufficient\'")',
    '"Digital technologies have the power to streamline pedagogical settings worldwide."': '“数字技术拥有精简全世界教育教学情境的权力。”\n> ("Digital technologies have the power to streamline pedagogical settings worldwide.")',
    
    '"The methodology involved in meta-analyses often obscures rather than illuminates what is needed for good policy decisions. The grouping of various factors into one \'[[Effect Size]]\' often hides the complexity of the issues."': '“元分析中涉及的方法论往往不仅不能启发，反而会掩盖良好政策决策所需的东西。将各种因素归集为一个‘[[Effect Size|效应量]]’，常常隐藏了问题的复杂性。”\n> ("The methodology involved in meta-analyses often obscures rather than illuminates what is needed for good policy decisions. The grouping of various factors into one \'[[Effect Size]]\' often hides the complexity of the issues.")',
    '"Although there are many published reports of educational research, you need to be very selective in identifying those that have something trustworthy to say about classroom teaching and learning."': '“尽管有许多已发表的教育研究报告，但在识别那些对课堂教学与学习有可信说法的报告时，你需要非常具有选择性。”\n> ("Although there are many published reports of educational research, you need to be very selective in identifying those that have something trustworthy to say about classroom teaching and learning.")',
    '"It is important that students preparing for teaching learn about the research process and how easily it leads to error rather than truth. They need to respect research but be acutely aware of its limitations."': '“对于准备从事教学的学生来说，了解研究过程以及它是多么容易导致错误而不是真相，这一点很重要。他们需要尊重研究，但也要敏锐地意识到它的局限性。”\n> ("It is important that students preparing for teaching learn about the research process and how easily it leads to error rather than truth. They need to respect research but be acutely aware of its limitations.")',
    
    '"To lead education beyond the agenda of what works, we need different approaches to research, including reflective approaches and critical studies addressing the power structures."': '“为了引领教育超越‘什么有效’的议程，我们需要不同的研究途径，包括反思性途径以及探讨权力结构的批判性研究。”\n> ("To lead education beyond the agenda of what works, we need different approaches to research, including reflective approaches and critical studies addressing the power structures.")',
    '"The rush to get accountability systems enshrined in legislation and bureaucratic practice is running ahead of the evidence on its behalf, and this is true despite the fact that the architects of the accountability systems are also vocal proponents of scientifically based decision making."': '“急于将问责制纳入立法和官僚实践的冲动，已经跑在了支持它的证据前面；尽管问责制的架构师们也是基于科学决策的大声疾呼者，但这一事实依然存在。”\n> ("The rush to get accountability systems enshrined in legislation and bureaucratic practice is running ahead of the evidence on its behalf, and this is true despite the fact that the architects of the accountability systems are also vocal proponents of scientifically based decision making.")'
}

def translate_quotes(filepath):
    try:
        with open(filepath, 'r', encoding='utf-8') as f:
            content = f.read()
            
        new_content = content
        for eng, chn in replacements.items():
            new_content = new_content.replace(eng, chn)
            
        if new_content != content:
            with open(filepath, 'w', encoding='utf-8') as f:
                f.write(new_content)
            return True
        return False
    except Exception as e:
        print(f"Error {e}")
        return False

def main():
    count = 0
    for root, dirs, files in os.walk('wiki/arguments/'):
        for file in files:
            if file.endswith('.md'):
                if translate_quotes(os.path.join(root, file)):
                    count += 1
                    print(f"Translated quotes in {file}")
    print(f"Total files updated: {count}")

if __name__ == '__main__':
    main()
