import os
import re

replacements = {
    # Argument_Slethaug_2010_InternationalEducation.md
    '"Educational systems tied to the formation of nation-state citizens and consumers bonded to local systems to the neglect of larger global forces are likely to become obsolete, while those that proactively engage globalization\'s new challenges are more likely to thrive."': '“那些与民族国家公民的培养和局限于本地系统的消费者紧密相连，而忽视更大全球力量的教育系统，很可能会变得过时；而那些主动应对全球化新挑战的教育系统则更有可能蓬勃发展。”\n> ("Educational systems tied to the formation of nation-state citizens and consumers bonded to local systems to the neglect of larger global forces are likely to become obsolete, while those that proactively engage globalization\'s new challenges are more likely to thrive.")',
    '"Perhaps more than most mainstream schools, therefore, [[International Schools]] must orient themselves to the market. They must provide curricula that are in demand at a price that can be afforded by their target clients, and must pay attention to changing demographic and economic forces."': '“因此，也许比大多数主流学校更重要的是，[[International Schools|国际学校]]必须面向市场。它们必须以目标客户能够承受的价格提供抢手的课程，并且必须关注不断变化的人口和经济力量。”\n> ("Perhaps more than most mainstream schools, therefore, [[International Schools]] must orient themselves to the market. They must provide curricula that are in demand at a price that can be afforded by their target clients, and must pay attention to changing demographic and economic forces.")',

    # Argument_Ryan_2010_ChineseLearner.md
    '"Chineseness is in effect defined in terms of deviance from Western norms, and generally as being interestingly different within mainstream, that is Western, psychology."': '“实际上，‘中国性（Chineseness）’是根据其偏离西方规范的程度来定义的，并且在主流（即西方）心理学中通常被认为是一种有趣的不同。”\n> ("Chineseness is in effect defined in terms of deviance from Western norms, and generally as being interestingly different within mainstream, that is Western, psychology.")',
    '"It is particularly infuriating to hear problems with such rhetorical styles attributed to imagined inadequacies in the student\'s education in their home country. ... Such analysis is misleading because it confuses differences in style of expression with a lack of academic rigour."': '“听到将这种修辞风格的问题归咎于学生在母国接受的教育存在假想的缺陷，尤其令人愤怒。……这种分析具有误导性，因为它将表达风格的差异与缺乏学术严谨性混为一谈。”\n> ("It is particularly infuriating to hear problems with such rhetorical styles attributed to imagined inadequacies in the student\'s education in their home country. ... Such analysis is misleading because it confuses differences in style of expression with a lack of academic rigour.")',
    '"There is a notable tendency in the applied linguistics literature to report the perceptions and reactions of Western instructors which, rather than being interrogated for ethnocentric bias and stereotyping, are validated by recourse to a Confucian heritage explanation which appears plausible rather than being empirically established."': '“在应用语言学文献中存在一种显著的倾向：报告西方教师的看法和反应，而没有质疑其民族中心主义偏见和刻板印象，反而是通过诉诸一种看似合理而非基于实证确立的儒家传统解释来证实它们。”\n> ("There is a notable tendency in the applied linguistics literature to report the perceptions and reactions of Western instructors which, rather than being interrogated for ethnocentric bias and stereotyping, are validated by recourse to a Confucian heritage explanation which appears plausible rather than being empirically established.")', 
    '"Good teaching and learning are \'the common treasures of humanity.\'"': '“良好的教与学是‘人类共同的财富’。”\n> ("Good teaching and learning are \'the common treasures of humanity.\'")',

    # Argument_Gilison_Wilson_2025_UniversityStartups.md
    '"Ask for money and they\'ll give you advice. Ask for advice and they\'ll give you money."': '“你问他们要钱，他们会给你建议。你问他们要建议，他们会给你钱。”\n> ("Ask for money and they\'ll give you advice. Ask for advice and they\'ll give you money.")',
    '"In fact, the odds are stacked against the [[University Spin-Out|university-based startup]] so much so that the successful ones are the true \'Uni-corns.\'"': '“事实上，各种不利因素对[[University Spin-Out|大学初创企业]]非常不利，以至于那些成功的企业才算是真正的‘独角兽’。”\n> ("In fact, the odds are stacked against the [[University Spin-Out|university-based startup]] so much so that the successful ones are the true \'Uni-corns.\'")',
    '"It was like [[Tracking]] a Yeti, where people have heard they exist but never witnessed one firsthand in the wild."': '“这就像在[[Tracking|追踪]]雪人，人们听说过它们的存在，但从未在野外亲眼目睹过。”\n> ("It was like [[Tracking]] a Yeti, where people have heard they exist but never witnessed one firsthand in the wild.")',
    '"The sure way to kill truly disruptive innovation is to have industry directly initiate startup and spin-out creation at universities."': '“扼杀真正颠覆性创新的必然方法，就是让产业界直接在大学发起初创企业和衍生企业的创建。”\n> ("The sure way to kill truly disruptive innovation is to have industry directly initiate startup and spin-out creation at universities.")',

    # Argument_LernerLam_2025_TransdisciplinaryExecutiveEd.md
    '"The evolution of complex, transdisciplinary thinking in response to these challenges—what some have characterized as advanced system thinking or convergence research—is not just confined to university campuses."': '“作为对这些挑战的回应，复杂的跨学科思维的演变——一些人将其描述为高级系统思维或融合研究——并不仅仅局限于大学校园。”\n> ("The evolution of complex, transdisciplinary thinking in response to these challenges—what some have characterized as advanced system thinking or convergence research—is not just confined to university campuses.")',
    '"Particularly for subject matter underlain by highly technical research in science and engineering, core scientific and engineering faculty might not be able to address the policy dynamics inherent in the grander challenge."': '“特别是对于以科学和工程领域高度技术性研究为基础的主题，核心科学和工程教员可能无法解决更宏大挑战中固有的政策动态问题。”\n> ("Particularly for subject matter underlain by highly technical research in science and engineering, core scientific and engineering faculty might not be able to address the policy dynamics inherent in the grander challenge.")',
    '"Columbia calls this its \'[[Fourth Generation University|Fourth Purpose]],\' a responsibility added to the traditional functions of scholarship, teaching and disciplinary service."': '“哥伦比亚大学将此称为其‘[[Fourth Generation University|第四使命]]’，这是在传统的学术、教学和学科服务功能之外增加的一项责任。”\n> ("Columbia calls this its \'[[Fourth Generation University|Fourth Purpose]],\' a responsibility added to the traditional functions of scholarship, teaching and disciplinary service.")',

    # Argument_Narayan_Spohrer_2025_Metrics.md
    '"It involves stakeholders with different outlooks and impact expectations. Moreover, the multidimensional nature of the impacts themselves means they are tangible and intangible, short- and long-term, direct and indirect, positive and negative, making their measurement process very complex."': '“它涉及具有不同观点和影响预期的利益相关者。此外，影响本身的多维性质意味着它们是有形和无形的、短期和长期的、直接和间接的、积极和消极的，这使得它们的衡量过程非常复杂。”\n> ("It involves stakeholders with different outlooks and impact expectations. Moreover, the multidimensional nature of the impacts themselves means they are tangible and intangible, short- and long-term, direct and indirect, positive and negative, making their measurement process very complex.")',
    '"The key to culture is trust based on history of UI relationship as well as the collaborative practice of clearly defining problems of mutual strong interest that can only be solved working together to achieve win-win outcomes. Failures are mutual learning experiences."': '“文化的关键在于建立在产学（UI）关系历史基础上的信任，以及明确界定只有通过合作实现双赢才能解决的共同强烈利益问题的合作实践。失败是共同学习的经验。”\n> ("The key to culture is trust based on history of UI relationship as well as the collaborative practice of clearly defining problems of mutual strong interest that can only be solved working together to achieve win-win outcomes. Failures are mutual learning experiences.")',
    '"AI will not replace service providers (e.g., industry researchers, academic faculty, etc.), but trusted service providers who use AI effectively and ethically will replace those who don\'t."': '“人工智能（AI）不会取代服务提供商（如产业研究人员、大学教员等），但是有效且符合伦理地使用 AI 的值得信赖的服务提供商，将取代那些不这么做的人。”\n> ("AI will not replace service providers (e.g., industry researchers, academic faculty, etc.), but trusted service providers who use AI effectively and ethically will replace those who don\'t.")',
    '"Success breeds success. Metrics associated with increasing flows of talent, publicity, publications and commercial offerings that highlight the new knowledge co-created are the outcomes that matter most in re-inventing a culture of [[University-Industry Collaboration|UI collaboration]] generation after generation."': '“成功孕育成功。与人才流动、宣传、出版物和商业产品的增加相关的指标突出了共同创造的新知识，这些是代代相传地重塑[[University-Industry Collaboration|产学合作]]文化中最关键的成果。”\n> ("Success breeds success. Metrics associated with increasing flows of talent, publicity, publications and commercial offerings that highlight the new knowledge co-created are the outcomes that matter most in re-inventing a culture of [[University-Industry Collaboration|UI collaboration]] generation after generation.")',
    '"Every change in business conditions and focus requires adjusting 6 R investment options and recalibrating metrics, incentives, rewards, and culture to fit the times."': '“商业条件和重点的每一次变化，都需要调整6 R投资选项，并重新校准指标、激励、奖励和文化以适应时代。”\n> ("Every change in business conditions and focus requires adjusting 6 R investment options and recalibrating metrics, incentives, rewards, and culture to fit the times.")',
    
    # Argument_Boccanfuso_Hall_2025_Alignment.md
    '"Innovation today often occurs at the \'interface,\' the interstitial space where industry and universities work with each other toward common goals."': '“当今的创新通常发生在‘界面’处，即产业界和大学为了共同目标而相互合作的间隙空间。”\n> ("Innovation today often occurs at the \'interface,\' the interstitial space where industry and universities work with each other toward common goals.")',
    '"Strength and impact are developed not solely through relationships between universities and industry but engagement."': '“实力与影响力的发展，不仅仅依靠大学与产业之间的关系，更在于深度参与。”\n> ("Strength and impact are developed not solely through relationships between universities and industry but engagement.")',
    '"Innovation does not readily occur in isolation."': '“创新很难在孤立的状态下发生。”\n> ("Innovation does not readily occur in isolation.")',
    '"There is substantial literature which suggests that continuous high levels of radical innovation in modern societies require diversity in organization forms, heterogeneity in organizational structures, diversity in ideas."': '“有大量文献表明，现代社会要持续保持高水平的激进创新，就需要组织形式的多样性、组织结构的异质性以及思想的多样性。”\n> ("There is substantial literature which suggests that continuous high levels of radical innovation in modern societies require diversity in organization forms, heterogeneity in organizational structures, diversity in ideas.")',
    
    # Argument_Boccanfuso_Hall_2025_OrgStrategy.md
    '"Relationships"、"partnerships"和"engagement"三个词的精微差异值得注意。如果一所 大学把办公室命名为"Corporate Relations Office"，它强调的是长期关系的维护——有点像客户关系管理（CRM）的逻辑。如果叫"Strategic Partnerships Office"，它暗示的是对等的、深度的、有共同战略目标的合作——"你和我一起定义合作的方向"。如果叫"Industry Engagement Office"，它强调的是互动的深度而非广度——"重要的不是你认识多少企业，而是你和多少 企业有实质性的合作"。': '“Relationships”、“partnerships”和“engagement”三个词的精微差异值得注意。如果一所大学把办公室命名为“Corporate Relations Office”，它强调的是长期关系的维护——有点像客户关系管理（CRM）的逻辑。如果叫“Strategic Partnerships Office”，它暗示的是对等的、深度的、有共同战略目标的合作——“你和我一起定义合作的方向”。如果叫“Industry Engagement Office”，它强调的是互动的深度而非广度——“重要的不是你认识多少企业，而是你和多少企业有实质性的合作”。\n> ("Relationships", "partnerships", and "engagement" carry subtle differences...)',

    # Argument_Parreira do Amaral_2022_geopolitics-knowledge.md
    '"The chapter argues that higher education, in this [[Tracking|setting]], is part of a New [[Geopolitics of Knowledge]] that refers to the integration of higher education in the imaginations and calculations of different actors aiming at asserting and/or improving their positions in the global [[Knowledge-Based Economy]]."': '“本章认为，在这种[[Tracking|背景]]下，高等教育是新[[Geopolitics of Knowledge|知识地缘政治]]的一部分，指的是将高等教育纳入不同行动者的想象和计算中，旨在主张和/或改善他们在全球[[Knowledge-Based Economy|知识经济]]中的地位。”\n> ("The chapter argues that higher education, in this [[Tracking|setting]], is part of a New [[Geopolitics of Knowledge]] that refers to the integration of higher education in the imaginations and calculations of different actors aiming at asserting and/or improving their positions in the global [[Knowledge-Based Economy]].")',
    
    # Argument_Zapp_2022_Springer.md
    '"Universities have entered the global governance landscape by strategically positioning themselves as global knowledge actors."': '“大学通过战略性地将自身定位为全球知识行动者，已经进入了全球治理的图景。”\n> ("Universities have entered the global governance landscape by strategically positioning themselves as global knowledge actors.")',
    '"With university knowledge becoming an important resource and asset in the global economy, the inter-university race for reputation, revenues, and researchers is oddly transposed to an unlevelled global geopolitical playing [[Champ|field]]."': '“随着大学知识成为全球经济中的重要资源和资产，大学间为声誉、收入和研究人员展开的竞争，被奇特地置换到了一个不平坦的全球地缘政治竞技[[Champ|场]]上。”\n> ("With university knowledge becoming an important resource and asset in the global economy, the inter-university race for reputation, revenues, and researchers is oddly transposed to an unlevelled global geopolitical playing [[Champ|field]].")',
    '"If universities want to preserve their unique status as independent knowledge arbiters in global governance and even reshuffle power structures traditionally skewed towards politics and markets, they have to make sure to not only follow the global agenda but begin to actively shape it."': '“如果大学想要在全球治理中保持其作为独立知识仲裁者的独特地位，甚至重组传统上偏向政治和市场的权力结构，它们必须确保不仅是追随全球议程，而且要开始积极地塑造它。”\n> ("If universities want to preserve their unique status as independent knowledge arbiters in global governance and even reshuffle power structures traditionally skewed towards politics and markets, they have to make sure to not only follow the global agenda but begin to actively shape it.")',

    # Argument_Partaken_2022_Springer.md
    '"Instead of such a static state of knowledge, the inquiry into geopolitics should pay more attention to the phenomena of \'[[Knowledge Transfer|knowledge in motion]]\' such as transfer, dissemination, pedagogy, indoctrination, theft, espionage, surveillance and censorship."': '“与其关注知识的这种静态，对地缘政治的探究应该更多地关注‘[[Knowledge Transfer|运动中的知识]]’现象，如转移、传播、教学法、灌输、窃取、间谍活动、监视和审查。”\n> ("Instead of such a static state of knowledge, the inquiry into geopolitics should pay more attention to the phenomena of \'[[Knowledge Transfer|knowledge in motion]]\' such as transfer, dissemination, pedagogy, indoctrination, theft, espionage, surveillance and censorship.")',
    '"The sovereignty lieth hid in knowledge"': '“主权隐藏在知识之中”\n> ("The sovereignty lieth hid in knowledge")',
    
    # Argument_Rizvi_2022_Springer.md
    '"along with"——Rizvi 不是要推翻既有解释，而是要**补充**一个被忽视的维度。': '“与……一起（along with）”——Rizvi 不是要推翻既有解释，而是要**补充**一个被忽视的维度。\n> ("along with")',
    '"Asia is rising but Asian wellbeing is not. The quality and quantity of growth are out of synch."': '“亚洲在崛起，但亚洲人的福祉却没有。增长的质量和数量不同步。”\n> ("Asia is rising but Asian wellbeing is not. The quality and quantity of growth are out of synch.")',
    '"language and text can create, shift, or maintain ideologies. In the case of [[GATS and Trade in Education Services|GATS]], the ideology reflects a new imperialism where more powerful countries retain developing countries as markets in which they continue to rule intellectually"': '“语言和文本可以创造、转移或维持意识形态。在[[GATS and Trade in Education Services|《服务贸易总协定》]]（GATS）的案例中，这种意识形态反映了一种新帝国主义，即更强大的国家将发展中国家保留为它们在知识上继续统治的市场。”\n> ("language and text can create, shift, or maintain ideologies. In the case of [[GATS and Trade in Education Services|GATS]], the ideology reflects a new imperialism where more powerful countries retain developing countries as markets in which they continue to rule intellectually")',
    '"the pandemic is a portal"': '“大流行是一扇传送门”\n> ("the pandemic is a portal")',
    '"The Asian Century is an Australian opportunity. As the global centre of gravity shifts to our region, the tyranny of distance is being replaced by the prospects of proximity"': '“亚洲世纪是澳大利亚的机遇。随着全球重心转移到我们这个地区，距离的暴政正在被相邻的前景所取代。”\n> ("The Asian Century is an Australian opportunity. As the global centre of gravity shifts to our region, the tyranny of distance is being replaced by the prospects of proximity")',
    
    # Argument_Amos_2022_Springer.md
    '"The diagnosis of scholars like Escobar and Haraway is clear enough: Without a significant change, not to say transformation of our mind-set, late modernity may as well be the last stage not only for humanity, but for the planet."': '“像 Escobar 和 Haraway 等学者的诊断已经足够清晰：如果不发生重大改变，或者说如果不转变我们的思维方式，晚期现代性很可能不仅是人类的最后阶段，也是这个星球的最后阶段。”\n> ("The diagnosis of scholars like Escobar and Haraway is clear enough: Without a significant change, not to say transformation of our mind-set, late modernity may as well be the last stage not only for humanity, but for the planet.")',
    '"What is needed then, is an educational theory that draws it all together. One that re-envisions public education with a non-compartmentalized organization of knowledge, that takes connectivity and [[Response-ability]], another term for caring as its organizing principle, one that encourages collaboration, is critical of ideologies that place the human being at the center of the universe, one that encourages non-dualistic thinking and the non-fixity of the self, pays attention to the multiple entanglements both material and non-material."': '“那么，我们需要的是一种能够将这一切结合起来的教育理论。这种理论用一种非碎片化的知识组织方式重新构想公共教育，将联结性和[[Response-ability|回应能力]]（关怀的另一个词）作为其组织原则，鼓励合作，批判将人类置于宇宙中心的意识形态，鼓励非二元思维和自我的非固定性，并关注物质和非物质的多重纠缠。”\n> ("What is needed then, is an educational theory that draws it all together. One that re-envisions public education with a non-compartmentalized organization of knowledge, that takes connectivity and [[Response-ability]], another term for caring as its organizing principle, one that encourages collaboration, is critical of ideologies that place the human being at the center of the universe, one that encourages non-dualistic thinking and the non-fixity of the self, pays attention to the multiple entanglements both material and non-material.")',
    
    # Argument_Rambla_2022_Springer.md
    '"The European Union has elaborated quite sophisticated imaginaries of education and innovation by means of [[Performance Indicators|policy instruments]] that use expert knowledge to draw certain geographical images of the member states and the regions within these states."': '“欧盟已经通过使用专家知识的[[Performance Indicators|政策工具]]，描绘出成员国及其内部区域的特定地理图像，从而构建了相当复杂的教育和创新想象。”\n> ("The European Union has elaborated quite sophisticated imaginaries of education and innovation by means of [[Performance Indicators|policy instruments]] that use expert knowledge to draw certain geographical images of the member states and the regions within these states.")',
    '"Performance indicators convey \'theories of change\' that highlight how policies activate certain mechanisms in a given context."': '“绩效指标传达了‘变革理论’，凸显了政策如何在特定情境中激活某些机制。”\n> ("Performance indicators convey \'theories of change\' that highlight how policies activate certain mechanisms in a given context.")',
    '"Performance indicators are a policy instrument that directly draws on scientific and technical legitimacy, and pushes policy actors towards competition."': '“绩效指标是一种直接利用科学和技术合法性的政策工具，它推动政策行动者走向竞争。”\n> ("Performance indicators are a policy instrument that directly draws on scientific and technical legitimacy, and pushes policy actors towards competition.")',
    '"Policy instruments \'select\' relevant policy issues in the arena of public debate and simultaneously induce actors to sideline other issues."': '“政策工具在公共辩论的舞台上‘选择’相关的政策议题，同时引导行动者边缘化其他议题。”\n> ("Policy instruments \'select\' relevant policy issues in the arena of public debate and simultaneously induce actors to sideline other issues.")',
    
    # Argument_Moisio_2022_Springer.md
    '"In this chapter, I seek to geopoliticize the purportedly geoeconomic present. In particular, I argue that the contemporary knowledge-intensive capitalism is a historically contingent geopolitical constellation that brings together a range of issues such as space, cities, states, human capital, education, and technology."': '“在本章中，我试图将据称是地缘经济的现在地缘政治化。具体而言，我主张当代知识密集型资本主义是一个具有历史偶然性的地缘政治星系，它将空间、城市、国家、人力资本、教育和技术等一系列议题汇聚在一起。”\n> ("In this chapter, I seek to geopoliticize the purportedly geoeconomic present. In particular, I argue that the contemporary knowledge-intensive capitalism is a historically contingent geopolitical constellation that brings together a range of issues such as space, cities, states, human capital, education, and technology.")',
    '"Capitalism perpetually strives, therefore, to create a social and physical landscape in its own image and requisite to its own needs at a particular point in time, only just as certainly to undermine, disrupt and even destroy that landscape at a later point in time."': '“因此，资本主义永远在努力按照自己的形象并为满足自己在特定时间点的需求，去创造一种社会和物质景观，然而在随后的时间点，它又同样确凿地会去破坏、扰乱甚至摧毁这种景观。”\n> ("Capitalism perpetually strives, therefore, to create a social and physical landscape in its own image and requisite to its own needs at a particular point in time, only just as certainly to undermine, disrupt and even destroy that landscape at a later point in time.")',
    '"The [[Geopolitics of Knowledge]]-based economization emanates from the very tension within the capitalist circulation process in space: the tension within the geography of accumulation between fixity and motion."': '“基于[[Geopolitics of Knowledge|知识地缘政治]]的经济化，源于资本主义空间循环过程内部的张力：积累地理中固定性与运动之间的张力。”\n> ("The [[Geopolitics of Knowledge]]-based economization emanates from the very tension within the capitalist circulation process in space: the tension within the geography of accumulation between fixity and motion.")',
    
    # Argument_Zelinka_2022_SCD_subjectivity.md
    '"It is not skills and competencies gained by subjects, but subjectivities, i.e. modes of self-conduct based on desired competencies, that become a source of production."': '“成为生产源泉的，不是主体获得的技能和能力，而是主体性，即基于期望能力的自我行为模式。”\n> ("It is not skills and competencies gained by subjects, but subjectivities, i.e. modes of self-conduct based on desired competencies, that become a source of production.")',
    '"Subjects are only disposable unless they acknowledge and enhance their self-entrepreneurial subjectivity and show passion for growth and a will to accelerate."': '“主体只有承认并增强其自我创业的主体性，表现出对成长的热情和加速的意愿，才不会沦为一次性用品（被随时抛弃）。”\n> ("Subjects are only disposable unless they acknowledge and enhance their self-entrepreneurial subjectivity and show passion for growth and a will to accelerate.")',
    '"The opposition to this kind of novel and innovative endeavor starts with questioning its very basis, i.e. its definition of subjects as knowledge-bearers."': '“对这种新颖和创新尝试的反对，始于质疑其根本基础，即质疑其将主体定义为知识承载者的做法。”\n> ("The opposition to this kind of novel and innovative endeavor starts with questioning its very basis, i.e. its definition of subjects as knowledge-bearers.")',
    
    # Argument_Creswell_2022_SAGE.md
    '"a set of interrelated [[Construct|constructs]] (variables), definitions, and propositions that presents a systematic view of phenomena by specifying relations among variables, with the purpose of explaining natural phenomena"': '“一组相互关联的[[Construct|构念]]（变量）、定义和命题，它们通过规定变量之间的关系来呈现对现象的系统看法，其目的是解释自然现象”\n> ("a set of interrelated [[Construct|constructs]] (variables), definitions, and propositions that presents a systematic view of phenomena by specifying relations among variables, with the purpose of explaining natural phenomena")',
    '"What remains to be explored, however, is..."': '“然而，有待进一步探索的是……”\n> ("What remains to be explored, however, is...")',
    '"Despite an increased interest..., it is surprising that so little empirical research has actually been conducted on the topic..."': '“尽管人们对……的兴趣日益浓厚，但令人惊讶的是，关于该主题实际进行的实证研究却如此之少……”\n> ("Despite an increased interest..., it is surprising that so little empirical research has actually been conducted on the topic...")',
    '"A [[Survey Research|survey design]] provides a quantitative description of trends, attitudes, and opinions of a population, or tests for associations among variables of a population, by studying a sample of that population."': '“[[Survey Research|调查设计]]通过研究一个总体的样本，提供对该总体趋势、态度和观点的量化描述，或检验总体中变量之间的关联。”\n> ("A [[Survey Research|survey design]] provides a quantitative description of trends, attitudes, and opinions of a population, or tests for associations among variables of a population, by studying a sample of that population.")',
    '"An [[Experimental Research|experimental design]] systematically manipulates one or more variables to evaluate how this manipulation affects an outcome (or outcomes) of interest. Importantly, an experiment isolates the effects of this manipulation by holding all other variables constant."': '“[[Experimental Research|实验设计]]系统地操纵一个或多个变量，以评估这种操纵如何影响感兴趣的结果。重要的是，实验通过保持所有其他变量不变来孤立这种操纵的效应。”\n> ("An [[Experimental Research|experimental design]] systematically manipulates one or more variables to evaluate how this manipulation affects an outcome (or outcomes) of interest. Importantly, an experiment isolates the effects of this manipulation by holding all other variables constant.")',
    '"Sample size determination is at its core a trade-off: A larger sample will provide more precision, but recruiting more participants is time-consuming and costly."': '“样本量的确定其核心是一种权衡：更大的样本将提供更高的精度，但招募更多的参与者既耗时又费钱。”\n> ("Sample size determination is at its core a trade-off: A larger sample will provide more precision, but recruiting more participants is time-consuming and costly.")',
    '"Sample size determination should be based on your analysis plans and expected outcomes."': '“样本量的确定应基于你的分析计划和预期结果。”\n> ("Sample size determination should be based on your analysis plans and expected outcomes.")',
    '"A [[Power Analysis]] can help you estimate a target sample size. ... This power analysis for sample size determination should be done during study planning and prior to enrolling any participants."': '“[[Power Analysis|功效分析]]可以帮助你估计目标样本量。……这种用于确定样本量的功效分析应当在研究计划阶段、招募任何参与者之前完成。”\n> ("A [[Power Analysis]] can help you estimate a target sample size. ... This power analysis for sample size determination should be done during study planning and prior to enrolling any participants.")',
    '"One of the principal features distinguishing an experiment from a survey study design is the use of [[Random Assignment]]."': '“区分实验与调查研究设计的一个主要特征是[[Random Assignment|随机分配]]的使用。”\n> ("One of the principal features distinguishing an experiment from a survey study design is the use of [[Random Assignment]].")',
    '"A [[Confidence Interval]] is a range of values (an interval) that describes a level of uncertainty around an estimated observed score. A confidence interval shows how good an estimated score might be."': '“[[Confidence Interval|置信区间]]是一个取值范围（一个区间），它描述了围绕估计观察分数的某种不确定性水平。置信区间显示了估计分数可能有多好。”\n> ("A [[Confidence Interval]] is a range of values (an interval) that describes a level of uncertainty around an estimated observed score. A confidence interval shows how good an estimated score might be.")',

    # Argument_Downey_2016_SoE.md
    '"When it comes to inequality, \'schooling is more part of the solution than part of the problem.\'"': '“在不平等问题上，‘学校教育在更大程度上是解决方案的一部分，而不是问题的一部分。’”\n> ("When it comes to inequality, \'schooling is more part of the solution than part of the problem.\'")',
    '"The proper way to assess schools\' effect on achievement gaps is not to focus solely on school year patterns but to compare the school year (treatment) and summer (control) patterns. Schools are compensatory whenever achievement trajectories are more equal when school is in versus out of session."': '“评估学校对成就差距影响的正确方法，不是仅仅关注学年模式，而是要比较学年（处理组）和夏季（对照组）的模式。只要在开学期间成就轨迹比放假期间更平等，学校就发挥了补偿作用。”\n> ("The proper way to assess schools\' effect on achievement gaps is not to focus solely on school year patterns but to compare the school year (treatment) and summer (control) patterns. Schools are compensatory whenever achievement trajectories are more equal when school is in versus out of session.")',
    '"The question is not whether it is possible via school reform to reduce achievement gaps; the question is whether school reform is the best strategy for reducing them."': '“问题不在于是否有可能通过学校改革来缩小成就差距；问题在于，学校改革是否是缩小差距的最佳策略。”\n> ("The question is not whether it is possible via school reform to reduce achievement gaps; the question is whether school reform is the best strategy for reducing them.")',
    '"A cynical—and entirely plausible—interpretation of the greater emphasis on reforming schools relative to reforming other institutions is that it serves a purpose: It distracts people from the real sources of inequality, thereby serving the interests of those who benefit from current social arrangements."': '“对于相较于改革其他机构更强调改革学校这一现象，一种愤世嫉俗——却完全合理——的解释是它服务于一种目的：它转移了人们对不平等的真正根源的注意力，从而服务于那些从当前社会安排中获益的人的利益。”\n> ("A cynical—and entirely plausible—interpretation of the greater emphasis on reforming schools relative to reforming other institutions is that it serves a purpose: It distracts people from the real sources of inequality, thereby serving the interests of those who benefit from current social arrangements.")',

    # Argument_Ball_2008_SR.md
    '"the sociology of education has created the \'conditions of possibility\' and an \'optics of power\'"': '“教育社会学创造了‘可能性的条件’和一种‘权力的光学’”\n> ("the sociology of education has created the \'conditions of possibility\' and an \'optics of power\'")',
    '"Education was no longer the solution but the problem."': '“教育不再是解决方案，而成了问题所在。”\n> ("Education was no longer the solution but the problem.")',
    '"effectiveness operates as a technology of normalisation."': '“有效性作为一种正常化的技术在运作。”\n> ("effectiveness operates as a technology of normalisation.")',

    # Argument_Golovchin_2019_ESC.md
    '"The variation of the [[Variable|variables]] used by Hattie exceeds 50%, which is higher than the statistical threshold of sample homogeneity (33%). ... Determining the strength of any effects in such a model, due to its instability, will likely not lead to the formation of objective conclusions."': '“Hattie 使用的[[Variable|变量]]变异系数超过了50%，高于样本同质性的统计阈值（33%）。……由于该模型的不稳定性，确定这种模型中任何效应的强度，很可能无法得出客观的结论。”\n> ("The variation of the [[Variable|variables]] used by Hattie exceeds 50%, which is higher than the statistical threshold of sample homogeneity (33%). ... Determining the strength of any effects in such a model, due to its instability, will likely not lead to the formation of objective conclusions.")',
    '"The implementation of Hattie\'s ideas within the framework of Russian educational policy is inapplicable, since it can cause negative consequences and extend the range of new problems (in particular, the increase in the bureaucratic functionality of the teaching profession in the pursuit of \'[[School Leadership]]\')."': '“在俄罗斯教育政策的框架内实施 Hattie 的观点是不适用的，因为这可能会造成负面后果并引发一系列新问题（特别是在追求‘[[School Leadership|学校领导力]]’的过程中，教师职业的官僚化职能增加）。”\n> ("The implementation of Hattie\'s ideas within the framework of Russian educational policy is inapplicable, since it can cause negative consequences and extend the range of new problems (in particular, the increase in the bureaucratic functionality of the teaching profession in the pursuit of \'[[School Leadership]]\').")',
    '"In education, however, there is little that \'works\' and little that \'does not work\'. The correct question is: \'Under what conditions will this work in school?\'"': '“然而，在教育中，几乎没有什么‘有效’，也几乎没有什么‘无效’。正确的问题是：‘在什么条件下，这在学校里会有效？’”\n> ("In education, however, there is little that \'works\' and little that \'does not work\'. The correct question is: \'Under what conditions will this work in school?\'")',
    '"The book is perceived as a panacea for the educational community, but as a result of taking this drug, the school will experience a short-term placebo effect."': '“这本书被教育界视为灵丹妙药，但服用这剂药的结果是，学校将经历一次短期的安慰剂效应。”\n> ("The book is perceived as a panacea for the educational community, but as a result of taking this drug, the school will experience a short-term placebo effect.")',

    # Argument_Simpson_2019_ERE.md
    '"In each of these examples, the educational intervention (and control activity and population and sample size, etc.) is exactly the same... yet the effect size varies from 0 to 0.4, to 0.6, to 4, to infinity."': '“在这些例子中，每一个的教育干预（以及控制活动、人群和样本量等）都完全相同……然而效应量却从0变到0.4，变到0.6，变到4，直至无穷大。”\n> ("In each of these examples, the educational intervention (and control activity and population and sample size, etc.) is exactly the same... yet the effect size varies from 0 to 0.4, to 0.6, to 4, to infinity.")',
    '"The enemy of clarity being noise — anything which acts to increase the noise of an experiment... will decrease effect size."': '“清晰的敌人是噪音——任何增加实验噪音的因素……都会降低效应量。”\n> ("The enemy of clarity being noise — anything which acts to increase the noise of an experiment... will decrease effect size.")',
    '"Mistaking effect size for a measure of educational importance or influence is, then, a category error."': '“那么，将效应量误认为是教育重要性或影响力的衡量标准，就是一个范畴错误。”\n> ("Mistaking effect size for a measure of educational importance or influence is, then, a category error.")',
    '"The appearance of [[Direct Instruction]] interventions like [[Feedback]] and meta-cognition at the top of meta-meta-analytic tables should be taken only as evidence that researchers have found it easier to conduct less noisy experiments in these areas compared to behaviour interventions or summer schools."': '“像[[Feedback|反馈]]和元认知这样的[[Direct Instruction|直接教学]]干预出现在元-元分析榜单顶部，只能被视为一种证据：表明与行为干预或暑期学校相比，研究者发现这些领域更容易开展低噪音的实验。”\n> ("The appearance of [[Direct Instruction]] interventions like [[Feedback]] and meta-cognition at the top of meta-meta-analytic tables should be taken only as evidence that researchers have found it easier to conduct less noisy experiments in these areas compared to behaviour interventions or summer schools.")',
    '"Forms of intervention are promoted as more effective when, in fact, the evidence merely indicates they are areas in which it may be easier to conduct clearer studies. This misidentification is leading policy, driving the use of scarce resources and causing major changes in teaching methods. There\'s the harm."': '“某些干预形式被推广为更有效，而事实上，证据仅仅表明在这些领域开展更清晰的研究可能更容易。这种错误识别正在引导政策，驱动稀缺资源的使用，并导致教学方法的重大改变。这就是危害所在。”\n> ("Forms of intervention are promoted as more effective when, in fact, the evidence merely indicates they are areas in which it may be easier to conduct clearer studies. This misidentification is leading policy, driving the use of scarce resources and causing major changes in teaching methods. There\'s the harm.")',
}

def translate_quotes(filepath):
    try:
        with open(filepath, 'r', encoding='utf-8') as f:
            content = f.read()
            
        new_content = content
        
        # dynamic typos or specifics
        for eng, chn in replacements.items():
            new_content = new_content.replace(eng, chn)
            
        if new_content != content:
            with open(filepath, 'w', encoding='utf-8') as f:
                f.write(new_content)
            return True
        return False
    except Exception as e:
        print(f"Error processing {filepath}: {e}")
        return False

def main():
    count = 0
    for root, dirs, files in os.walk('wiki/arguments/'):
        for file in files:
            if file.endswith('.md'):
                if translate_quotes(os.path.join(root, file)):
                    count += 1
                    print(f"Translated quotes in {file}")
    print(f"Total files updated: {count}")

if __name__ == '__main__':
    main()
