import os

replacements = {
    # Argument_Cowen_2019_ERE.md
    '"What I propose here is that there are features of EBE that make it attractive, or at least uncontroversial and safe, to policymakers."': '“我在这里提出的是，EBE（循证教育）的某些特征使其对政策制定者具有吸引力，或者至少是无争议和安全的。”\n> ("What I propose here is that there are features of EBE that make it attractive, or at least uncontroversial and safe, to policymakers.")',
    '"Even a systematic review or meta-analysis of many high-quality RCTs provides little epistemic warrant for applying to a new population."': '“即使是对许多高质量 RCT 进行的系统综述或元分析，也不能为将其应用于新人群提供多少认识论保证。”\n> ("Even a systematic review or meta-analysis of many high-quality RCTs provides little epistemic warrant for applying to a new population.")',
    '"The advantage of formal criteria for the sovereign is that she does not have to explore the details of research evidence, pass judgement on specific interventions, or evaluate the approach and conduct of individual experts."': '“正式标准对统治者（决策者）的优势在于，她不必探索研究证据的细节，不必对特定干预做出判断，也不必评估个别专家的途径和行为。”\n> ("The advantage of formal criteria for the sovereign is that she does not have to explore the details of research evidence, pass judgement on specific interventions, or evaluate the approach and conduct of individual experts.")',
    '"Being selective about one\'s use of evidence is easy enough... But, increasingly, policymakers do more than determine what evidence to acknowledge and which to ignore. They now develop policies defining what sort of research evidence is worth producing in the first place."': '“在证据使用上挑挑拣拣是很容易的……但是，政策制定者越来越多地不仅决定承认哪些证据、忽略哪些证据。他们现在制定政策来界定首先什么类型的研究证据值得生产。”\n> ("Being selective about one\'s use of evidence is easy enough... But, increasingly, policymakers do more than determine what evidence to acknowledge and which to ignore. They now develop policies defining what sort of research evidence is worth producing in the first place.")',
    '"The point of departure for EBE is that there are given resources available... This avoids an important conclusion of academic research in education: Resources matter."': '“EBE 的出发点是存在既定的可用资源……这就回避了教育学术研究的一个重要结论：资源很重要。”\n> ("The point of departure for EBE is that there are given resources available... This avoids an important conclusion of academic research in education: Resources matter.")',
    '"The experimental paradigm exerts disproportionate influence on policymakers because of the particular role it can play in guiding the policy of a centralised bureaucracy."': '“实验范式对政策制定者产生了不成比例的影响，因为它在指导中央集权官僚机构政策方面能发挥特殊作用。”\n> ("The experimental paradigm exerts disproportionate influence on policymakers because of the particular role it can play in guiding the policy of a centralised bureaucracy.")',
    '"The attraction of novelty also offers some explanation. New governments tend to displace incumbents by pointing out their failed policies so there is a strong imperative to introduce innovative reforms."': '“新奇性的吸引力也提供了一些解释。新政府倾向于通过指出前任失败的政策来取代他们，因此引入创新性改革有着强烈的必要性。”\n> ("The attraction of novelty also offers some explanation. New governments tend to displace incumbents by pointing out their failed policies so there is a strong imperative to introduce innovative reforms.")',
    '"It\'s not what you spend, it\'s the way that you spend it …that\'s what gets results.\' This avoids an important conclusion: Resources matter. More funding going into schools leads to predictably improved results."': '“‘不是你花了多少钱，而是你花钱的方式……那才是产生结果的原因。’这回避了一个重要结论：资源很重要。投入学校的资金越多，就能带来可预测的成绩提升。”\n> ("It\'s not what you spend, it\'s the way that you spend it …that\'s what gets results.\' This avoids an important conclusion: Resources matter. More funding going into schools leads to predictably improved results.")',

    # Argument_Wrigley_2019_ERE.md
    '"It is our contention that these appeals to science use a flawed and stereotyped vernacular image or \'folk-view\' (Thomas, 2012, p. 28) of the natural sciences for rhetorical effect but fail to probe sufficiently into the true characteristics of science."': '“我们的观点是，这些对科学的诉诸为了修辞效果，使用了一种有缺陷且刻板的自然科学的白话形象或‘民间观点’（Thomas, 2012, p. 28），但未能充分探究科学的真正特征。”\n> ("It is our contention that these appeals to science use a flawed and stereotyped vernacular image or \'folk-view\' (Thomas, 2012, p. 28) of the natural sciences for rhetorical effect but fail to probe sufficiently into the true characteristics of science.")',
    '"At every stage of the meta-analytic review, simplifications are made. [[Hypothesis|hypotheses]] are abridged, studies are dropped, programme details are filtered out, contextual information is eliminated, selected findings are utilized, averages are taken, estimates are made."': '“在元分析综述的每个阶段，都在进行简化。[[Hypothesis|假设]]被删减，研究被舍弃，项目细节被过滤掉，情境信息被消除，只利用选定的发现，计算平均值，并做出估计。”\n> ("At every stage of the meta-analytic review, simplifications are made. [[Hypothesis|hypotheses]] are abridged, studies are dropped, programme details are filtered out, contextual information is eliminated, selected findings are utilized, averages are taken, estimates are made.")',
    '"The intention of this paper is to demonstrate that many advocates of evidence-based teaching work with too simple a notion of \'science\', with serious negative consequences."': '“本文的意图是证明，许多循证教学的倡导者使用的是一种过于简单的‘科学’概念，这带来了严重的负面后果。”\n> ("The intention of this paper is to demonstrate that many advocates of evidence-based teaching work with too simple a notion of \'science\', with serious negative consequences.")',
    '"It is, therefore, fundamentally unscientific to try to explain social phenomena by applying the wrong level of scientific methodology."': '“因此，试图通过应用错误层级的科学方法论来解释社会现象，从根本上就是不科学的。”\n> ("It is, therefore, fundamentally unscientific to try to explain social phenomena by applying the wrong level of scientific methodology.")',
    '"Effective experiments demand the artificial controls imposed by the reductive methodology of the experimenter, but we must never forget that as a consequence they provide at best only a very simplified model, perhaps even a false one, of what happens in the blooming, buzzing, interactive confusion of life at large."': '“有效的实验需要实验者用还原主义方法论强加的人为控制，但我们绝不能忘记，其结果是它们充其量只能提供一个非常简化的模型——甚至可能是一个虚假的模型——来反映整体生活中那种繁盛的、嗡嗡作响的、互动的混乱状态中究竟发生了什么。”\n> ("Effective experiments demand the artificial controls imposed by the reductive methodology of the experimenter, but we must never forget that as a consequence they provide at best only a very simplified model, perhaps even a false one, of what happens in the blooming, buzzing, interactive confusion of life at large.")',
    '"Whereas drugs trials try to eliminate the human factor because \'human volition is seen as a contaminator\', social change is brought about through the human agent."': '“药物试验试图消除人为因素，因为‘人的意志被视为一种污染源’，而社会变革则是通过人的能动性带来的。”\n> ("Whereas drugs trials try to eliminate the human factor because \'human volition is seen as a contaminator\', social change is brought about through the human agent.")',
    '"The result of a [[Meta-analysis]] should never be an average; it should be a graph."': '“[[Meta-analysis|元分析]]的结果绝不应该是一个平均数；它应该是一张图表。”\n> ("The result of a [[Meta-analysis]] should never be an average; it should be a graph.")',
    '"Education is marked by a [[Multiplicity]] of aims — acquisition of factual knowledge, skilled performance, problem solving, longer term cognitive development, aesthetic or ethical qualities, socialisation."': '“教育的特点在于目的的[[Multiplicity|多重性]]——获取事实知识、熟练的表现、解决问题、长期的认知发展、审美或伦理品质、社会化。”\n> ("Education is marked by a [[Multiplicity]] of aims — acquisition of factual knowledge, skilled performance, problem solving, longer term cognitive development, aesthetic or ethical qualities, socialisation.")',
    '"In the name of \'science\' and in conjunction with the dynamics of high-stakes accountability systems, we are witnessing an anti-enlightenment closing down of ways of understanding and engaging with the world."': '“以‘科学’之名，结合高风险问责系统的动态机制，我们正在目睹一种反启蒙的现象：各种理解和参与世界的方式正在被封闭。”\n> ("In the name of \'science\' and in conjunction with the dynamics of high-stakes accountability systems, we are witnessing an anti-enlightenment closing down of ways of understanding and engaging with the world.")',

    # Argument_Wiliam_2019_ERE.md
    '"In educational research, \'What works\' is usually the wrong question because almost anything works somewhere, and nothing works everywhere. A better question is, \'Under what circumstances does this work\'."': '“在教育研究中，‘什么有效’通常是一个错误的问题，因为几乎任何东西在某些地方都会有效，而没有任何东西在所有地方都有效。一个更好的问题是，‘在什么情况下这会有效’。”\n> ("In educational research, \'What works\' is usually the wrong question because almost anything works somewhere, and nothing works everywhere. A better question is, \'Under what circumstances does this work\'.")',
    '"The entire project of [[Evidence-Based Education]] can never be successful. Any claims about \'what works\' are necessarily local... Moreover, such claims will be provisional, in that new findings, insights, and understandings will bring previously credible interpretations of research studies into question."': '“[[Evidence-Based Education|循证教育]]的整个计划永远不可能成功。任何关于‘什么有效’的主张都必然是局部的……此外，这些主张将是暂时性的，因为新的发现、洞见和理解将对以前可信的研究解释提出质疑。”\n> ("The entire project of [[Evidence-Based Education]] can never be successful. Any claims about \'what works\' are necessarily local... Moreover, such claims will be provisional, in that new findings, insights, and understandings will bring previously credible interpretations of research studies into question.")',
    '"Identifying how teachers, schools, districts, and jurisdictions can most profitably direct their efforts will always involve the application of judgement, taking into account local knowledge, the likely relevance of findings from other contexts, the feasibility of proposed reforms (politically, economically, culturally, etc.), and a whole host of other factors."': '“确定教师、学校、学区和司法管辖区如何才能最有利地引导他们的努力，将永远涉及判断的应用，需要考虑到本地知识、其他情境中发现的可能相关性、提议改革的可行性（政治、经济、文化等方面），以及一大堆其他因素。”\n> ("Identifying how teachers, schools, districts, and jurisdictions can most profitably direct their efforts will always involve the application of judgement, taking into account local knowledge, the likely relevance of findings from other contexts, the feasibility of proposed reforms (politically, economically, culturally, etc.), and a whole host of other factors.")',
    '"The synthesising the results of a number of meta-analyses by some weighted combination of the effect sizes generated by the individual meta-analyses – what has come to be called [[Meta-meta-analysis]] – has absolutely no role in educational policymaking."': '“通过将各个元分析生成的效应量进行某种加权组合，来综合多个元分析的结果——即后来被称为[[Meta-meta-analysis|元-元分析]]的方法——在教育政策制定中绝对没有作用。”\n> ("The synthesising the results of a number of meta-analyses by some weighted combination of the effect sizes generated by the individual meta-analyses – what has come to be called [[Meta-meta-analysis]] – has absolutely no role in educational policymaking.")',

    # Argument_Schaffar_2024_CogentEdu.md
    '"The aim of [[Phenomenon-Based Learning]] (PhBL) is to provide such an educational approach."': '“[[Phenomenon-Based Learning|现象导向学习]]（PhBL）的目的正是提供这样一种教育方法。”\n> ("The aim of [[Phenomenon-Based Learning]] (PhBL) is to provide such an educational approach.")',
    '"The Finnish curriculum is still structured according to traditional school subjects..."': '“芬兰的课程仍然是按照传统的学校科目构建的……”\n> ("The Finnish curriculum is still structured according to traditional school subjects...")',
    '"The PhBL approach is neither a salvation approach, nor a quick-fix-method..."': '“PhBL 方法既不是救世主的途径，也不是一种快速修复法……”\n> ("The PhBL approach is neither a salvation approach, nor a quick-fix-method...")',

    # Argument_Slavin_2002_ER.md
    '"If Rip Van Winkle had been a physician, a farmer, or an engineer, he would be unemployable if he awoke today. If he had been a good elementary school teacher in the 19th century, he would probably be a good elementary school teacher today."': '“如果瑞普·凡·温克尔（Rip Van Winkle，传说中沉睡多年的人）是一位医生、农民或工程师，那么他今天醒来将无法被雇佣。但如果他在19世纪是一位优秀的小学教师，那么他今天可能仍然是一位优秀的小学教师。”\n> ("If Rip Van Winkle had been a physician, a farmer, or an engineer, he would be unemployable if he awoke today. If he had been a good elementary school teacher in the 19th century, he would probably be a good elementary school teacher today.")',
    '"At the dawn of the 21st century, educational research is finally entering the 20th century."': '“在21世纪的曙光中，教育研究终于正在进入20世纪。”\n> ("At the dawn of the 21st century, educational research is finally entering the 20th century.")',
    '"Educational practice does change over time, but the change process more resembles the pendulum swings of taste characteristic of art or fashion (think hemlines) rather than the progressive improvements characteristic of science and technology."': '“教育实践确实随着时间而改变，但其变化过程更像是艺术或时尚（想想裙摆长度）品味的钟摆摆动，而不是科学技术所特征的渐进式改善。”\n> ("Educational practice does change over time, but the change process more resembles the pendulum swings of taste characteristic of art or fashion (think hemlines) rather than the progressive improvements characteristic of science and technology.")',
    '"Before the Wright brothers, many inventors launched airplanes that were based on exactly the same scientifically based aviation research as the Wright brothers used at Kitty Hawk, but the other airplanes never got off the ground."': '“在莱特兄弟之前，许多发明家发射的飞机都是基于与莱特兄弟在基蒂霍克使用的完全相同的基于科学的航空研究，但其他飞机从未飞离地面。”\n> ("Before the Wright brothers, many inventors launched airplanes that were based on exactly the same scientifically based aviation research as the Wright brothers used at Kitty Hawk, but the other airplanes never got off the ground.")',
    '"Once we have dozens or hundreds of randomized or carefully matched experiments going on each year on all aspects of educational practice, we will begin to make steady, irreversible progress. Until then, we are merely riding the pendulum of educational fashion."': '“一旦我们每年在教育实践的各个方面开展数十或数百项随机或仔细匹配的实验，我们将开始取得稳步、不可逆转的进展。在此之前，我们只是在乘坐教育时尚的钟摆。”\n> ("Once we have dozens or hundreds of randomized or carefully matched experiments going on each year on all aspects of educational practice, we will begin to make steady, irreversible progress. Until then, we are merely riding the pendulum of educational fashion.")',

    # Argument_Kraft_2023_ER.md
    '"This is the benchmark that matters most."': '“这是最要紧的基准。”\n> ("This is the benchmark that matters most.")'
}

def translate_quotes(filepath):
    try:
        with open(filepath, 'r', encoding='utf-8') as f:
            content = f.read()
            
        new_content = content
        for eng, chn in replacements.items():
            new_content = new_content.replace(eng, chn)
            
        if new_content != content:
            with open(filepath, 'w', encoding='utf-8') as f:
                f.write(new_content)
            return True
        return False
    except Exception as e:
        print(f"Error processing {filepath}: {e}")
        return False

def main():
    count = 0
    for root, dirs, files in os.walk('wiki/arguments/'):
        for file in files:
            if file.endswith('.md'):
                if translate_quotes(os.path.join(root, file)):
                    count += 1
                    print(f"Translated quotes in {file}")
    print(f"Total files updated: {count}")

if __name__ == '__main__':
    main()
